export const optionsReligion = [
  { id: 0, label: 'Islam', value: 'Islam' },
  { id: 1, label: 'Protestan', value: 'Protestan' },
  { id: 2, label: 'Catholic', value: 'Catholic' },
  { id: 3, label: 'Hindu', value: 'Hindu' },
  { id: 4, label: 'Budha', value: 'Budha' },
  { id: 5, label: 'Konghucu', value: 'Konghucu' },
]
export const optionsMartialStatus = [
  { id: 0, label: 'Married', value: 'Married' },
  { id: 1, label: 'Single', value: 'Single' },
  { id: 2, label: 'Widowed', value: 'Widowed' },
  { id: 3, label: 'Divorced', value: 'Divorced' },
]
export const optionsBloodType = [
  { id: 0, label: 'A', value: 'A' },
  { id: 1, label: 'B', value: 'B' },
  { id: 2, label: 'AB', value: 'AB' },
  { id: 3, label: 'O', value: 'O' },
]
export const optionsCountryOfbirth = [
  { id: 0, label: 'Afghanistan', value: 'Afghanistan' },
  { id: 1, label: 'Albania', value: 'Albania' },
  { id: 2, label: 'Algeria', value: 'Algeria' },
  { id: 3, label: 'Andorra', value: 'Andorra' },
  { id: 4, label: 'Angola', value: 'Angola' },
  { id: 5, label: 'Antigua & Deps', value: 'Antigua & Deps' },
  { id: 6, label: 'Argentina', value: 'Argentina' },
  { id: 7, label: 'Armenia', value: 'Armenia' },
  { id: 8, label: 'Australia', value: 'Australia' },
  { id: 9, label: 'Austria', value: 'Austria' },
  { id: 10, label: 'Azerbaijan', value: 'Azerbaijan' },
  { id: 11, label: 'Bahamas', value: 'Bahamas' },
  { id: 12, label: 'Bahrain', value: 'Bahrain' },
  { id: 13, label: 'Bangladesh', value: 'Bangladesh' },
  { id: 14, label: 'Barbados', value: 'Barbados' },
  { id: 15, label: 'Belarus', value: 'Belarus' },
  { id: 16, label: 'Belgium', value: 'Belgium' },
  { id: 17, label: 'Belize', value: 'Belize' },
  { id: 18, label: 'Benin', value: 'Benin' },
  { id: 19, label: 'Bhutan', value: 'Bhutan' },
  { id: 20, label: 'Bolivia', value: 'Bolivia' },
  { id: 21, label: 'Bosnia Herzegovina', value: 'Bosnia Herzegovina' },
  { id: 22, label: 'Botswana', value: 'Botswana' },
  { id: 23, label: 'Brazil', value: 'Brazil' },
  { id: 24, label: 'Brunei', value: 'Brunei' },
  { id: 25, label: 'Bulgaria', value: 'Bulgaria' },
  { id: 26, label: 'Burkina', value: 'Burkina' },
  { id: 27, label: 'Burundi', value: 'Burundi' },
  { id: 28, label: 'Cambodia', value: 'Cambodia' },
  { id: 29, label: 'Cameroon', value: 'Cameroon' },
  { id: 30, label: 'Canada', value: 'Canada' },
  { id: 31, label: 'Cape Verde', value: 'Cape Verde' },
  { id: 32, label: 'Central African Rep', value: 'Central African Rep' },
  { id: 33, label: 'Chad', value: 'Chad' },
  { id: 34, label: 'Chile', value: 'Chile' },
  { id: 35, label: 'China', value: 'China' },
  { id: 36, label: 'Colombia', value: 'Colombia' },
  { id: 37, label: 'Comoros', value: 'Comoros' },
  { id: 38, label: 'Congo', value: 'Congo' },
  { id: 39, label: 'Congo {Democratic Rep}', value: 'Congo {Democratic Rep}' },
  { id: 40, label: 'Costa Rica', value: 'Costa Rica' },
  { id: 41, label: 'Croatia', value: 'Croatia' },
  { id: 42, label: 'Cuba', value: 'Cuba' },
  { id: 43, label: 'Cyprus', value: 'Cyprus' },
  { id: 44, label: 'Czech Republic', value: 'Czech Republic' },
  { id: 45, label: 'Denmark', value: 'Denmark' },
  { id: 46, label: 'Djibouti', value: 'Djibouti' },
  { id: 47, label: 'Dominica', value: 'Dominica' },
  { id: 48, label: 'Dominican Republic', value: 'Dominican Republic' },
  { id: 49, label: 'East Timor', value: 'East Timor' },
  { id: 50, label: 'Ecuador', value: 'Ecuador' },
  { id: 51, label: 'Egypt', value: 'Egypt' },
  { id: 52, label: 'El Salvador', value: 'El Salvador' },
  { id: 53, label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { id: 54, label: 'Eritrea', value: 'Eritrea' },
  { id: 55, label: 'Estonia', value: 'EgEstoniaypt' },
  { id: 56, label: 'Ethiopia', value: 'Ethiopia' },
  { id: 57, label: 'Fiji', value: 'Fiji' },
  { id: 58, label: 'Finland', value: 'Finland' },
  { id: 59, label: 'France', value: 'France' },
  { id: 60, label: 'Gabon', value: 'Gabon' },
  { id: 61, label: 'Gambia', value: 'Gambia' },
  { id: 62, label: 'Georgia', value: 'Georgia' },
  { id: 63, label: 'Germany', value: 'Germany' },
  { id: 64, label: 'Ghana', value: 'Ghana' },
  { id: 65, label: 'Greece', value: 'Greece' },
  { id: 66, label: 'Grenada', value: 'Grenada' },
  { id: 67, label: 'Guatemala', value: 'Guatemala' },
  { id: 68, label: 'Guinea', value: 'Guinea' },
  { id: 69, label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
  { id: 70, label: 'Guyana', value: 'Guyana' },
  { id: 71, label: 'Haiti', value: 'Haiti' },
  { id: 72, label: 'Honduras', value: 'Honduras' },
  { id: 73, label: 'Hungary', value: 'Hungary' },
  { id: 74, label: 'Iceland', value: 'Iceland' },
  { id: 75, label: 'India', value: 'India' },
  { id: 76, label: 'Indonesia', value: 'Indonesia' },
  { id: 77, label: 'Iran', value: 'Iran' },
  { id: 78, label: 'Iraq', value: 'Iraq' },
  { id: 79, label: 'Ireland {Republic}', value: 'Ireland {Republic}' },
  { id: 80, label: 'Israel', value: 'Israel' },
  { id: 81, label: 'Italy', value: 'Italy' },
  { id: 82, label: 'Ivory Coast', value: 'Ivory Coast' },
  { id: 83, label: 'Jamaica', value: 'Jamaica' },
  { id: 84, label: 'Japan', value: 'Japan' },
  { id: 85, label: 'Jordan', value: 'Jordan' },
  { id: 86, label: 'Kazakhstan', value: 'Kazakhstan' },
  { id: 87, label: 'Kenya', value: 'Kenya' },
  { id: 88, label: 'Kiribati', value: 'Kiribati' },
  { id: 89, label: 'Korea North', value: 'Korea North' },
  { id: 90, label: 'Korea South', value: 'Korea South' },
  { id: 91, label: 'Kosovo', value: 'Kosovo' },
  { id: 92, label: 'Kuwait', value: 'Kuwait' },
  { id: 93, label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
  { id: 94, label: 'Laos', value: 'Laos' },
  { id: 95, label: 'Latvia', value: 'Latvia' },
  { id: 96, label: 'Lebanon', value: 'Lebanon' },
  { id: 97, label: 'Lesotho', value: 'Lesotho' },
  { id: 98, label: 'Liberia', value: 'Liberia' },
  { id: 99, label: 'Libya', value: 'Libya' },
  { id: 100, label: 'Liechtenstein', value: 'Liechtenstein' },
  { id: 101, label: 'Lithuania', value: 'Lithuania' },
  { id: 102, label: 'Luxembourg', value: 'Luxembourg' },
  { id: 103, label: 'Macedonia', value: 'Macedonia' },
  { id: 104, label: 'Madagascar', value: 'Madagascar' },
  { id: 105, label: 'Malawi', value: 'Malawi' },
  { id: 106, label: 'Malaysia', value: 'Malaysia' },
  { id: 107, label: 'Maldives', value: 'Maldives' },
  { id: 108, label: 'Mali', value: 'Mali' },
  { id: 109, label: 'Malta', value: 'Malta' },
  { id: 110, label: 'Marshall Islands', value: 'Marshall Islands' },
  { id: 111, label: 'Mauritania', value: 'Mauritania' },
  { id: 112, label: 'Mauritius', value: 'Mauritius' },
  { id: 113, label: 'Mexico', value: 'Mexico' },
  { id: 114, label: 'Micronesia', value: 'Micronesia' },
  { id: 115, label: 'Moldova', value: 'Moldova' },
  { id: 116, label: 'Monaco', value: 'Monaco' },
  { id: 117, label: 'Mongolia', value: 'Mongolia' },
  { id: 118, label: 'Montenegro', value: 'Montenegro' },
  { id: 119, label: 'Morocco', value: 'Morocco' },
  { id: 120, label: 'Mozambique', value: 'Mozambique' },
  { id: 121, label: 'Myanmar, {Burma}', value: 'Myanmar, {Burma}' },
  { id: 122, label: 'Namibia', value: 'Namibia' },
  { id: 123, label: 'Nauru', value: 'Nauru' },
  { id: 124, label: 'Nepal', value: 'Nepal' },
  { id: 125, label: 'Netherlands', value: 'Netherlands' },
  { id: 126, label: 'New Zealand', value: 'New Zealand' },
  { id: 127, label: 'Nicaragua', value: 'Nicaragua' },
  { id: 128, label: 'Niger', value: 'Niger' },
  { id: 129, label: 'Nigeria', value: 'Nigeria' },
  { id: 130, label: 'Norway', value: 'Norway' },
  { id: 131, label: 'Oman', value: 'Oman' },
  { id: 132, label: 'Pakistan', value: 'Pakistan' },
  { id: 133, label: 'Palau', value: 'Palau' },
  { id: 134, label: 'Panama', value: 'Panama' },
  { id: 135, label: 'Papua New Guinea', value: 'Papua New Guinea' },
  { id: 136, label: 'Paraguay', value: 'Paraguay' },
  { id: 137, label: 'Peru', value: 'Peru' },
  { id: 138, label: 'Philippines', value: 'Philippines' },
  { id: 139, label: 'Poland', value: 'Poland' },
  { id: 140, label: 'Portugal', value: 'Portugal' },
  { id: 141, label: 'Qatar', value: 'Qatar' },
  { id: 142, label: 'Romania', value: 'Romania' },
  { id: 143, label: 'Russian Federation', value: 'Russian Federation' },
  { id: 144, label: 'Rwanda', value: 'Rwanda' },
  { id: 145, label: 'St Kitts & Nevis', value: 'St Kitts & Nevis' },
  { id: 146, label: 'St Lucia', value: 'St Lucia' },
  { id: 147, label: 'Saint Vincent & the Grenadines', value: 'Saint Vincent & the Grenadines' },
  { id: 148, label: 'Samoa', value: 'Samoa' },
  { id: 149, label: 'San Marino', value: 'San Marino' },
  { id: 150, label: 'Sao Tome & Principe', value: 'Sao Tome & Principe' },
  { id: 151, label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { id: 152, label: 'Senegal', value: 'Senegal' },
  { id: 153, label: 'Serbia', value: 'Serbia' },
  { id: 154, label: 'Seychelles', value: 'Seychelles' },
  { id: 155, label: 'Sierra Leone', value: 'Sierra Leone' },
  { id: 156, label: 'Singapore', value: 'Singapore' },
  { id: 157, label: 'Slovakia', value: 'Slovakia' },
  { id: 158, label: 'Slovenia', value: 'Slovenia' },
  { id: 159, label: 'Solomon Islands', value: 'Solomon Islands' },
  { id: 160, label: 'Somalia', value: 'Somalia' },
  { id: 161, label: 'South Africa', value: 'South Africa' },
  { id: 162, label: 'South Sudan', value: 'South Sudan' },
  { id: 163, label: 'Spain', value: 'Spain' },
  { id: 164, label: 'Sri Lanka', value: 'Sri Lanka' },
  { id: 165, label: 'Sudan', value: 'Sudan' },
  { id: 166, label: 'Suriname', value: 'Suriname' },
  { id: 167, label: 'Swaziland', value: 'Swaziland' },
  { id: 168, label: 'Sweden', value: 'Sweden' },
  { id: 169, label: 'Switzerland', value: 'Switzerland' },
  { id: 170, label: 'Syria', value: 'Syria' },
  { id: 171, label: 'Taiwan', value: 'Taiwan' },
  { id: 172, label: 'Tajikistan', value: 'Tajikistan' },
  { id: 173, label: 'Tanzania', value: 'Tanzania' },
  { id: 174, label: 'Thailand', value: 'Thailand' },
  { id: 175, label: 'Togo', value: 'Togo' },
  { id: 176, label: 'Tonga', value: 'Tonga' },
  { id: 177, label: 'Trinidad & Tobago', value: 'Trinidad & Tobago' },
  { id: 178, label: 'Tunisia', value: 'Tunisia' },
  { id: 179, label: 'Turkey', value: 'Turkey' },
  { id: 180, label: 'Turkmenistan', value: 'Turkmenistan' },
  { id: 181, label: 'Tuvalu', value: 'Tuvalu' },
  { id: 182, label: 'Uganda', value: 'Uganda' },
  { id: 183, label: 'Ukraine', value: 'Ukraine' },
  { id: 184, label: 'United Arab Emirates', value: 'United Arab Emirates' },
  { id: 185, label: 'United Kingdom', value: 'United Kingdom' },
  { id: 186, label: 'United States', value: 'United States' },
  { id: 187, label: 'Uruguay', value: 'Uruguay' },
  { id: 188, label: 'Uzbekistan', value: 'Uzbekistan' },
  { id: 189, label: 'Vanuatu', value: 'Vanuatu' },
  { id: 190, label: 'Vatican City', value: 'Vatican City' },
  { id: 191, label: 'Venezuela', value: 'Venezuela' },
  { id: 192, label: 'Vietnam', value: 'Vietnam' },
  { id: 193, label: 'Yemen', value: 'Yemen' },
  { id: 194, label: 'Zambia', value: 'Zambia' },
  { id: 195, label: 'Zimbabwe', value: 'Zimbabwe' },
]

export const optionsCountry = [
  { id: 0, label: 'Indonesia', value: 'Indonesia' },
]
export const optionsProvince = [
  { id: 0, label: 'Province 1', value: 'Province 1' },
  { id: 1, label: 'Province 2', value: 'Province 2' },
  { id: 2, label: 'Province 3', value: 'Province 3' },
]
export const optionsCity = [
  { id: 0, label: 'City 1', value: 'City 1' },
  { id: 1, label: 'City 2', value: 'City 2' },
  { id: 2, label: 'City 3', value: 'City 3' },
]
export const optionsDistrict = [
  { id: 0, label: 'District 1', value: 'District 1' },
  { id: 1, label: 'District 2', value: 'District 2' },
  { id: 2, label: 'District 3', value: 'District 3' },
]
export const optionsZipCode = [
  { id: 0, label: 'Zip Code 1', value: 'Zip Code 1' },
  { id: 1, label: 'Zip Code 2', value: 'Zip Code 2' },
  { id: 2, label: 'Zip Code 3', value: 'Zip Code 3' },
]
export const optionsPhoneCode = [
  { id: 0, label: '+93', value: '93' },
  { id: 1, label: '+27', value: '27' },
  { id: 2, label: '+236', value: '236' },
  { id: 3, label: '+355', value: '355' },
  { id: 4, label: '+213', value: '213' },
  { id: 5, label: '+1', value: '1' },
  { id: 6, label: '+376', value: '376' },
  { id: 7, label: '+244', value: '244' },
  { id: 8, label: '+1-268', value: '1268' },
  { id: 9, label: '+966', value: '966' },
  { id: 10, label: '+54', value: '54' },
  { id: 11, label: '+374', value: '373' },
  { id: 12, label: '+61', value: '61' },
  { id: 13, label: '+43', value: '43' },
  { id: 14, label: '+994', value: '995' },
  { id: 15, label: '+1-242', value: '1242' },
  { id: 16, label: '+973', value: '973' },
  { id: 17, label: '+880', value: '880' },
  { id: 18, label: '+1-246', value: '1246' },
  { id: 19, label: '+31', value: '31' },
  { id: 20, label: '+375', value: '375' },
  { id: 21, label: '+32', value: '32' },
  { id: 22, label: '+501', value: '501' },
  { id: 23, label: '+229', value: '229' },
  { id: 24, label: '+975', value: '975' },
  { id: 25, label: '+591', value: '591' },
  { id: 26, label: '+387', value: '387' },
  { id: 27, label: '+267', value: '267' },
  { id: 28, label: '+55', value: '55' },
  { id: 29, label: '+44', value: '44' },
  { id: 30, label: '+673', value: '673' },
  { id: 31, label: '+359', value: '359' },
  { id: 32, label: '+226', value: '226' },
  { id: 33, label: '+257', value: '257' },
  { id: 34, label: '+420', value: '420' },
  { id: 35, label: '+235', value: '235' },
  { id: 36, label: '+56', value: '56' },
  { id: 37, label: '+86', value: '86' },
  { id: 38, label: '+45', value: '45' },
  { id: 39, label: '+253', value: '253' },
  { id: 40, label: '+1-767', value: '1767' },
  { id: 41, label: '+593', value: '593' },
  { id: 42, label: '+503', value: '503' },
  { id: 43, label: '+291', value: '291' },
  { id: 44, label: '+372', value: '372' },
  { id: 45, label: '+251', value: '251' },
  { id: 46, label: '+679', value: '679' },
  { id: 47, label: '+63', value: '63' },
  { id: 48, label: '+358', value: '358' },
  { id: 49, label: '+241', value: '241' },
  { id: 50, label: '+220', value: '220' },
  { id: 51, label: '+995', value: '995' },
  { id: 52, label: '+233', value: '233' },
  { id: 53, label: '+1-473', value: '1473' },
  { id: 54, label: '+502', value: '502' },
  { id: 55, label: '+224', value: '224' },
  { id: 56, label: '+245', value: '245' },
  { id: 57, label: '+240', value: '240' },
  { id: 58, label: '+592', value: '592' },
  { id: 59, label: '+509', value: '509' },
  { id: 60, label: '+504', value: '504' },
  { id: 61, label: '+36', value: '36' },
  { id: 62, label: '+852', value: '852' },
  { id: 63, label: '+91', value: '91' },
  { id: 64, label: '+62', value: '62' },
  { id: 65, label: '+964', value: '964' },
  { id: 66, label: '+98', value: '98' },
  { id: 67, label: '+353', value: '353' },
  { id: 68, label: '+354', value: '354' },
  { id: 69, label: '+972', value: '972' },
  { id: 70, label: '+39', value: '39' },
  { id: 71, label: '+1-876', value: '1876' },
  { id: 72, label: '+81', value: '81' },
  { id: 73, label: '+49', value: '49' },
  { id: 74, label: '+962', value: '962' },
  { id: 75, label: '+855', value: '855' },
  { id: 76, label: '+237', value: '237' },
  { id: 77, label: '+1', value: '1' },
  { id: 78, label: '+7', value: '7' },
  { id: 79, label: '+254', value: '254' },
  { id: 80, label: '+996', value: '996' },
  { id: 81, label: '+686', value: '686' },
  { id: 82, label: '+57', value: '57' },
  { id: 83, label: '+269', value: '269' },
  { id: 84, label: '+243', value: '243' },
  { id: 85, label: '+82', value: '82' },
  { id: 86, label: '+850', value: '850' },
  { id: 87, label: '+506', value: '506' },
  { id: 88, label: '+385', value: '385' },
  { id: 89, label: '+53', value: '53' },
  { id: 90, label: '+965', value: '965' },
  { id: 91, label: '+856', value: '856' },
  { id: 92, label: '+371', value: '371' },
  { id: 93, label: '+961', value: '961' },
  { id: 94, label: '+266', value: '266' },
  { id: 95, label: '+231', value: '231' },
  { id: 96, label: '+218', value: '218' },
  { id: 97, label: '+423', value: '423' },
  { id: 98, label: '+370', value: '370' },
  { id: 99, label: '+352', value: '352' },
  { id: 100, label: '+261', value: '261' },
  { id: 101, label: '+853', value: '853' },
  { id: 102, label: '+389', value: '389' },
  { id: 103, label: '+960', value: '960' },
  { id: 104, label: '+265', value: '265' },
  { id: 105, label: '+60', value: '60' },
  { id: 106, label: '+223', value: '223' },
  { id: 107, label: '+356', value: '356' },
  { id: 108, label: '+212', value: '212' },
  { id: 109, label: '+692', value: '692' },
  { id: 110, label: '+222', value: '222' },
  { id: 111, label: '+230', value: '230' },
  { id: 112, label: '+52', value: '52' },
  { id: 113, label: '+20', value: '20' },
  { id: 114, label: '+691', value: '691' },
  { id: 115, label: '+373', value: '373' },
  { id: 116, label: '+377', value: '377' },
  { id: 117, label: '+976', value: '976' },
  { id: 118, label: '+382', value: '382' },
  { id: 119, label: '+258', value: '258' },
  { id: 120, label: '+95', value: '95' },
  { id: 121, label: '+264', value: '264' },
  { id: 122, label: '+674', value: '674' },
  { id: 123, label: '+977', value: '977' },
  { id: 124, label: '+227', value: '227' },
  { id: 125, label: '+234', value: '234' },
  { id: 126, label: '+505', value: '505' },
  { id: 127, label: '+47', value: '47' },
  { id: 128, label: '+968', value: '968' },
  { id: 129, label: '+92', value: '92' },
  { id: 130, label: '+680', value: '680' },
  { id: 131, label: '+507', value: '507' },
  { id: 132, label: '+225', value: '225' },
  { id: 133, label: '+675', value: '675' },
  { id: 134, label: '+595', value: '595' },
  { id: 135, label: '+33', value: '33' },
  { id: 136, label: '+51', value: '51' },
  { id: 137, label: '+48', value: '48' },
  { id: 138, label: '+351', value: '351' },
  { id: 139, label: '+974', value: '974' },
  { id: 140, label: '+242', value: '242' },
  { id: 141, label: '+1-829', value: '1829' },
  { id: 142, label: '+40', value: '40' },
  { id: 143, label: '+7', value: '7' },
  { id: 144, label: '+250', value: '250' },
  { id: 145, label: '+1-869', value: '1869' },
  { id: 146, label: '+1-758', value: '1758' },
  { id: 147, label: '+1-784', value: '1784' },
  { id: 148, label: '+685', value: '685' },
  { id: 149, label: '+378', value: '378' },
  { id: 150, label: '+239', value: '239' },
  { id: 151, label: '+64', value: '64' },
  { id: 152, label: '+221', value: '221' },
  { id: 153, label: '+381', value: '381' },
  { id: 154, label: '+248', value: '248' },
  { id: 155, label: '+232', value: '232' },
  { id: 156, label: '+65', value: '65' },
  { id: 157, label: '+357', value: '357' },
  { id: 158, label: '+386', value: '386' },
  { id: 159, label: '+421', value: '421' },
  { id: 160, label: '+677', value: '677' },
  { id: 161, label: '+252', value: '252' },
  { id: 162, label: '+34', value: '34' },
  { id: 163, label: '+94', value: '94' },
  { id: 164, label: '+249', value: '249' },
  { id: 165, label: '+211', value: '211' },
  { id: 166, label: '+963', value: '963' },
  { id: 167, label: '+597', value: '597' },
  { id: 168, label: '+268', value: '268' },
  { id: 169, label: '+46', value: '46' },
  { id: 170, label: '+41', value: '41' },
  { id: 171, label: '+992', value: '992' },
  { id: 172, label: '+238', value: '238' },
  { id: 173, label: '+255', value: '255' },
  { id: 174, label: '+886', value: '886' },
  { id: 175, label: '+66', value: '66' },
  { id: 176, label: '+670', value: '670' },
  { id: 177, label: '+228', value: '228' },
  { id: 178, label: '+676', value: '676' },
  { id: 179, label: '+1-868', value: '1868' },
  { id: 180, label: '+216', value: '216' },
  { id: 181, label: '+90', value: '90' },
  { id: 182, label: '+993', value: '993' },
  { id: 183, label: '+688', value: '688' },
  { id: 184, label: '+256', value: '256' },
  { id: 185, label: '+380', value: '380' },
  { id: 186, label: '+971', value: '971' },
  { id: 187, label: '+598', value: '598' },
  { id: 188, label: '+998', value: '998' },
  { id: 189, label: '+678', value: '678' },
  { id: 190, label: '+58', value: '58' },
  { id: 191, label: '+84', value: '84' },
  { id: 192, label: '+967', value: '967' },
  { id: 193, label: '+30', value: '30' },
  { id: 194, label: '+260', value: '260' },
  { id: 195, label: '+263', value: '263' },
]

export const optionsIdType = [
  { id: 0, label: 'KTP', value: 'KTP' },
]
export const optionsTaxStatus = [
  { id: 0, label: 'TK/0', value: 'TK/0' },
  { id: 1, label: 'TK/1', value: 'TK/1' },
  { id: 2, label: 'TK/2', value: 'TK/2' },
  { id: 3, label: 'TK/3', value: 'TK/3' },
  { id: 4, label: 'K/0', value: 'K/0' },
  { id: 5, label: 'K/1', value: 'K/1' },
  { id: 6, label: 'K/2', value: 'K/2' },
  { id: 7, label: 'K/3', value: 'K/3' },
]

export const optionsFieldOfStudy = [
  {
    id: 2,
    label: 'GENERAL AGRICULTURE',
    value: 'GENERAL AGRICULTURE',
  },
  {
    id: 3,
    label: 'AGRICULTURE PRODUCTION AND MANAGEMENT',
    value: 'AGRICULTURE PRODUCTION AND MANAGEMENT',
  },
  {
    id: 4,
    label: 'AGRICULTURAL ECONOMICS',
    value: 'AGRICULTURAL ECONOMICS',
  },
  {
    id: 5,
    label: 'ANIMAL SCIENCES',
    value: 'ANIMAL SCIENCES',
  },
  {
    id: 6,
    label: 'FOOD SCIENCE',
    value: 'FOOD SCIENCE',
  },
  {
    id: 7,
    label: 'PLANT SCIENCE AND AGRONOMY',
    value: 'PLANT SCIENCE AND AGRONOMY',
  },
  {
    id: 8,
    label: 'SOIL SCIENCE',
    value: 'SOIL SCIENCE',
  },
  {
    id: 9,
    label: 'MISCELLANEOUS AGRICULTURE',
    value: 'MISCELLANEOUS AGRICULTURE',
  },
  {
    id: 10,
    label: 'FORESTRY',
    value: 'FORESTRY',
  },
  {
    id: 11,
    label: 'NATURAL RESOURCES MANAGEMENT',
    value: 'NATURAL RESOURCES MANAGEMENT',
  },
  {
    id: 12,
    label: 'FINE ARTS',
    value: 'FINE ARTS',
  },
  {
    id: 13,
    label: 'DRAMA AND THEATER ARTS',
    value: 'DRAMA AND THEATER ARTS',
  },
  {
    id: 14,
    label: 'MUSIC',
    value: 'MUSIC',
  },
  {
    id: 15,
    label: 'VISUAL AND PERFORMING ARTS',
    value: 'VISUAL AND PERFORMING ARTS',
  },
  {
    id: 16,
    label: 'COMMERCIAL ART AND GRAPHIC DESIGN',
    value: 'COMMERCIAL ART AND GRAPHIC DESIGN',
  },
  {
    id: 17,
    label: 'FILM VIDEO AND PHOTOGRAPHIC ARTS',
    value: 'FILM VIDEO AND PHOTOGRAPHIC ARTS',
  },
  {
    id: 18,
    label: 'STUDIO ARTS',
    value: 'STUDIO ARTS',
  },
  {
    id: 19,
    label: 'MISCELLANEOUS FINE ARTS',
    value: 'MISCELLANEOUS FINE ARTS',
  },
  {
    id: 20,
    label: 'ENVIRONMENTAL SCIENCE',
    value: 'ENVIRONMENTAL SCIENCE',
  },
  {
    id: 21,
    label: 'BIOLOGY',
    value: 'BIOLOGY',
  },
  {
    id: 22,
    label: 'BIOCHEMICAL SCIENCES',
    value: 'BIOCHEMICAL SCIENCES',
  },
  {
    id: 23,
    label: 'BOTANY',
    value: 'BOTANY',
  },
  {
    id: 24,
    label: 'MOLECULAR BIOLOGY',
    value: 'MOLECULAR BIOLOGY',
  },
  {
    id: 25,
    label: 'ECOLOGY',
    value: 'ECOLOGY',
  },
  {
    id: 26,
    label: 'GENETICS',
    value: 'GENETICS',
  },
  {
    id: 27,
    label: 'MICROBIOLOGY',
    value: 'MICROBIOLOGY',
  },
  {
    id: 28,
    label: 'PHARMACOLOGY',
    value: 'PHARMACOLOGY',
  },
  {
    id: 29,
    label: 'PHYSIOLOGY',
    value: 'PHYSIOLOGY',
  },
  {
    id: 30,
    label: 'ZOOLOGY',
    value: 'ZOOLOGY',
  },
  {
    id: 31,
    label: 'NEUROSCIENCE',
    value: 'NEUROSCIENCE',
  },
  {
    id: 32,
    label: 'MISCELLANEOUS BIOLOGY',
    value: 'MISCELLANEOUS BIOLOGY',
  },
  {
    id: 33,
    label: 'COGNITIVE SCIENCE AND BIOPSYCHOLOGY',
    value: 'COGNITIVE SCIENCE AND BIOPSYCHOLOGY',
  },
  {
    id: 34,
    label: 'GENERAL BUSINESS',
    value: 'GENERAL BUSINESS',
  },
  {
    id: 35,
    label: 'ACCOUNTING',
    value: 'ACCOUNTING',
  },
  {
    id: 36,
    label: 'ACTUARIAL SCIENCE',
    value: 'ACTUARIAL SCIENCE',
  },
  {
    id: 37,
    label: 'BUSINESS MANAGEMENT AND ADMINISTRATION',
    value: 'BUSINESS MANAGEMENT AND ADMINISTRATION',
  },
  {
    id: 38,
    label: 'OPERATIONS LOGISTICS AND E-COMMERCE',
    value: 'OPERATIONS LOGISTICS AND E-COMMERCE',
  },
  {
    id: 39,
    label: 'BUSINESS ECONOMICS',
    value: 'BUSINESS ECONOMICS',
  },
  {
    id: 40,
    label: 'MARKETING AND MARKETING RESEARCH',
    value: 'MARKETING AND MARKETING RESEARCH',
  },
  {
    id: 41,
    label: 'FINANCE',
    value: 'FINANCE',
  },
  {
    id: 42,
    label: 'HUMAN RESOURCES AND PERSONNEL MANAGEMENT',
    value: 'HUMAN RESOURCES AND PERSONNEL MANAGEMENT',
  },
  {
    id: 43,
    label: 'INTERNATIONAL BUSINESS',
    value: 'INTERNATIONAL BUSINESS',
  },
  {
    id: 44,
    label: 'HOSPITALITY MANAGEMENT',
    value: 'HOSPITALITY MANAGEMENT',
  },
  {
    id: 45,
    label: 'MANAGEMENT INFORMATION SYSTEMS AND STATISTICS',
    value: 'MANAGEMENT INFORMATION SYSTEMS AND STATISTICS',
  },
  {
    id: 46,
    label: 'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION',
    value: 'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION',
  },
  {
    id: 47,
    label: 'COMMUNICATIONS',
    value: 'COMMUNICATIONS',
  },
  {
    id: 48,
    label: 'JOURNALISM',
    value: 'JOURNALISM',
  },
  {
    id: 49,
    label: 'MASS MEDIA',
    value: 'MASS MEDIA',
  },
  {
    id: 50,
    label: 'ADVERTISING AND PUBLIC RELATIONS',
    value: 'ADVERTISING AND PUBLIC RELATIONS',
  },
  {
    id: 51,
    label: 'COMMUNICATION TECHNOLOGIES',
    value: 'COMMUNICATION TECHNOLOGIES',
  },
  {
    id: 52,
    label: 'COMPUTER AND INFORMATION SYSTEMS',
    value: 'COMPUTER AND INFORMATION SYSTEMS',
  },
  {
    id: 53,
    label: 'COMPUTER PROGRAMMING AND DATA PROCESSING',
    value: 'COMPUTER PROGRAMMING AND DATA PROCESSING',
  },
  {
    id: 54,
    label: 'COMPUTER SCIENCE',
    value: 'COMPUTER SCIENCE',
  },
  {
    id: 55,
    label: 'INFORMATION SCIENCES',
    value: 'INFORMATION SCIENCES',
  },
  {
    id: 56,
    label: 'COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY',
    value: 'COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY',
  },
  {
    id: 57,
    label: 'COMPUTER NETWORKING AND TELECOMMUNICATIONS',
    value: 'COMPUTER NETWORKING AND TELECOMMUNICATIONS',
  },
  {
    id: 58,
    label: 'MATHEMATICS',
    value: 'MATHEMATICS',
  },
  {
    id: 59,
    label: 'APPLIED MATHEMATICS',
    value: 'APPLIED MATHEMATICS',
  },
  {
    id: 60,
    label: 'STATISTICS AND DECISION SCIENCE',
    value: 'STATISTICS AND DECISION SCIENCE',
  },
  {
    id: 61,
    label: 'MATHEMATICS AND COMPUTER SCIENCE',
    value: 'MATHEMATICS AND COMPUTER SCIENCE',
  },
  {
    id: 62,
    label: 'GENERAL EDUCATION',
    value: 'GENERAL EDUCATION',
  },
  {
    id: 63,
    label: 'EDUCATIONAL ADMINISTRATION AND SUPERVISION',
    value: 'EDUCATIONAL ADMINISTRATION AND SUPERVISION',
  },
  {
    id: 64,
    label: 'SCHOOL STUDENT COUNSELING',
    value: 'SCHOOL STUDENT COUNSELING',
  },
  {
    id: 65,
    label: 'ELEMENTARY EDUCATION',
    value: 'ELEMENTARY EDUCATION',
  },
  {
    id: 66,
    label: 'MATHEMATICS TEACHER EDUCATION',
    value: 'MATHEMATICS TEACHER EDUCATION',
  },
  {
    id: 67,
    label: 'PHYSICAL AND HEALTH EDUCATION TEACHING',
    value: 'PHYSICAL AND HEALTH EDUCATION TEACHING',
  },
  {
    id: 68,
    label: 'EARLY CHILDHOOD EDUCATION',
    value: 'EARLY CHILDHOOD EDUCATION',
  },
  {
    id: 69,
    label: 'SCIENCE AND COMPUTER TEACHER EDUCATION',
    value: 'SCIENCE AND COMPUTER TEACHER EDUCATION',
  },
  {
    id: 70,
    label: 'SECONDARY TEACHER EDUCATION',
    value: 'SECONDARY TEACHER EDUCATION',
  },
  {
    id: 71,
    label: 'SPECIAL NEEDS EDUCATION',
    value: 'SPECIAL NEEDS EDUCATION',
  },
  {
    id: 72,
    label: 'SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION',
    value: 'SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION',
  },
  {
    id: 73,
    label: 'TEACHER EDUCATION: MULTIPLE LEVELS',
    value: 'TEACHER EDUCATION: MULTIPLE LEVELS',
  },
  {
    id: 74,
    label: 'LANGUAGE AND DRAMA EDUCATION',
    value: 'LANGUAGE AND DRAMA EDUCATION',
  },
  {
    id: 75,
    label: 'ART AND MUSIC EDUCATION',
    value: 'ART AND MUSIC EDUCATION',
  },
  {
    id: 76,
    label: 'MISCELLANEOUS EDUCATION',
    value: 'MISCELLANEOUS EDUCATION',
  },
  {
    id: 77,
    label: 'LIBRARY SCIENCE',
    value: 'LIBRARY SCIENCE',
  },
  {
    id: 78,
    label: 'ARCHITECTURE',
    value: 'ARCHITECTURE',
  },
  {
    id: 79,
    label: 'GENERAL ENGINEERING',
    value: 'GENERAL ENGINEERING',
  },
  {
    id: 80,
    label: 'AEROSPACE ENGINEERING',
    value: 'AEROSPACE ENGINEERING',
  },
  {
    id: 81,
    label: 'BIOLOGICAL ENGINEERING',
    value: 'BIOLOGICAL ENGINEERING',
  },
  {
    id: 82,
    label: 'ARCHITECTURAL ENGINEERING',
    value: 'ARCHITECTURAL ENGINEERING',
  },
  {
    id: 83,
    label: 'BIOMEDICAL ENGINEERING',
    value: 'BIOMEDICAL ENGINEERING',
  },
  {
    id: 84,
    label: 'CHEMICAL ENGINEERING',
    value: 'CHEMICAL ENGINEERING',
  },
  {
    id: 85,
    label: 'CIVIL ENGINEERING',
    value: 'CIVIL ENGINEERING',
  },
  {
    id: 86,
    label: 'COMPUTER ENGINEERING',
    value: 'COMPUTER ENGINEERING',
  },
  {
    id: 87,
    label: 'ELECTRICAL ENGINEERING',
    value: 'ELECTRICAL ENGINEERING',
  },
  {
    id: 88,
    label: 'ENGINEERING MECHANICS PHYSICS AND SCIENCE',
    value: 'ENGINEERING MECHANICS PHYSICS AND SCIENCE',
  },
  {
    id: 89,
    label: 'ENVIRONMENTAL ENGINEERING',
    value: 'ENVIRONMENTAL ENGINEERING',
  },
  {
    id: 90,
    label: 'GEOLOGICAL AND GEOPHYSICAL ENGINEERING',
    value: 'GEOLOGICAL AND GEOPHYSICAL ENGINEERING',
  },
  {
    id: 91,
    label: 'INDUSTRIAL AND MANUFACTURING ENGINEERING',
    value: 'INDUSTRIAL AND MANUFACTURING ENGINEERING',
  },
  {
    id: 92,
    label: 'MATERIALS ENGINEERING AND MATERIALS SCIENCE',
    value: 'MATERIALS ENGINEERING AND MATERIALS SCIENCE',
  },
  {
    id: 93,
    label: 'MECHANICAL ENGINEERING',
    value: 'MECHANICAL ENGINEERING',
  },
  {
    id: 94,
    label: 'METALLURGICAL ENGINEERING',
    value: 'METALLURGICAL ENGINEERING',
  },
  {
    id: 95,
    label: 'MINING AND MINERAL ENGINEERING',
    value: 'MINING AND MINERAL ENGINEERING',
  },
  {
    id: 96,
    label: 'NAVAL ARCHITECTURE AND MARINE ENGINEERING',
    value: 'NAVAL ARCHITECTURE AND MARINE ENGINEERING',
  },
  {
    id: 97,
    label: 'NUCLEAR ENGINEERING',
    value: 'NUCLEAR ENGINEERING',
  },
  {
    id: 98,
    label: 'PETROLEUM ENGINEERING',
    value: 'PETROLEUM ENGINEERING',
  },
  {
    id: 99,
    label: 'MISCELLANEOUS ENGINEERING',
    value: 'MISCELLANEOUS ENGINEERING',
  },
  {
    id: 100,
    label: 'ENGINEERING TECHNOLOGIES',
    value: 'ENGINEERING TECHNOLOGIES',
  },
  {
    id: 101,
    label: 'ENGINEERING AND INDUSTRIAL MANAGEMENT',
    value: 'ENGINEERING AND INDUSTRIAL MANAGEMENT',
  },
  {
    id: 102,
    label: 'ELECTRICAL ENGINEERING TECHNOLOGY',
    value: 'ELECTRICAL ENGINEERING TECHNOLOGY',
  },
  {
    id: 103,
    label: 'INDUSTRIAL PRODUCTION TECHNOLOGIES',
    value: 'INDUSTRIAL PRODUCTION TECHNOLOGIES',
  },
  {
    id: 104,
    label: 'MECHANICAL ENGINEERING RELATED TECHNOLOGIES',
    value: 'MECHANICAL ENGINEERING RELATED TECHNOLOGIES',
  },
  {
    id: 105,
    label: 'MISCELLANEOUS ENGINEERING TECHNOLOGIES',
    value: 'MISCELLANEOUS ENGINEERING TECHNOLOGIES',
  },
  {
    id: 106,
    label: 'MATERIALS SCIENCE',
    value: 'MATERIALS SCIENCE',
  },
  {
    id: 107,
    label: 'NUTRITION SCIENCES',
    value: 'NUTRITION SCIENCES',
  },
  {
    id: 108,
    label: 'GENERAL MEDICAL AND HEALTH SERVICES',
    value: 'GENERAL MEDICAL AND HEALTH SERVICES',
  },
  {
    id: 109,
    label: 'COMMUNICATION DISORDERS SCIENCES AND SERVICES',
    value: 'COMMUNICATION DISORDERS SCIENCES AND SERVICES',
  },
  {
    id: 110,
    label: 'HEALTH AND MEDICAL ADMINISTRATIVE SERVICES',
    value: 'HEALTH AND MEDICAL ADMINISTRATIVE SERVICES',
  },
  {
    id: 111,
    label: 'MEDICAL ASSISTING SERVICES',
    value: 'MEDICAL ASSISTING SERVICES',
  },
  {
    id: 112,
    label: 'MEDICAL TECHNOLOGIES TECHNICIANS',
    value: 'MEDICAL TECHNOLOGIES TECHNICIANS',
  },
  {
    id: 113,
    label: 'HEALTH AND MEDICAL PREPARATORY PROGRAMS',
    value: 'HEALTH AND MEDICAL PREPARATORY PROGRAMS',
  },
  {
    id: 114,
    label: 'NURSING',
    value: 'NURSING',
  },
  {
    id: 115,
    label: 'PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION',
    value: 'PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION',
  },
  {
    id: 116,
    label: 'TREATMENT THERAPY PROFESSIONS',
    value: 'TREATMENT THERAPY PROFESSIONS',
  },
  {
    id: 117,
    label: 'COMMUNITY AND PUBLIC HEALTH',
    value: 'COMMUNITY AND PUBLIC HEALTH',
  },
  {
    id: 118,
    label: 'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS',
    value: 'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS',
  },
  {
    id: 119,
    label: 'AREA ETHNIC AND CIVILIZATION STUDIES',
    value: 'AREA ETHNIC AND CIVILIZATION STUDIES',
  },
  {
    id: 120,
    label: 'LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE',
    value: 'LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE',
  },
  {
    id: 121,
    label: 'FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES',
    value: 'FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES',
  },
  {
    id: 122,
    label: 'OTHER FOREIGN LANGUAGES',
    value: 'OTHER FOREIGN LANGUAGES',
  },
  {
    id: 123,
    label: 'ENGLISH LANGUAGE AND LITERATURE',
    value: 'ENGLISH LANGUAGE AND LITERATURE',
  },
  {
    id: 124,
    label: 'COMPOSITION AND RHETORIC',
    value: 'COMPOSITION AND RHETORIC',
  },
  {
    id: 125,
    label: 'LIBERAL ARTS',
    value: 'LIBERAL ARTS',
  },
  {
    id: 126,
    label: 'HUMANITIES',
    value: 'HUMANITIES',
  },
  {
    id: 127,
    label: 'INTERCULTURAL AND INTERNATIONAL STUDIES',
    value: 'INTERCULTURAL AND INTERNATIONAL STUDIES',
  },
  {
    id: 128,
    label: 'PHILOSOPHY AND RELIGIOUS STUDIES',
    value: 'PHILOSOPHY AND RELIGIOUS STUDIES',
  },
  {
    id: 129,
    label: 'THEOLOGY AND RELIGIOUS VOCATIONS',
    value: 'THEOLOGY AND RELIGIOUS VOCATIONS',
  },
  {
    id: 130,
    label: 'ANTHROPOLOGY AND ARCHEOLOGY',
    value: 'ANTHROPOLOGY AND ARCHEOLOGY',
  },
  {
    id: 131,
    label: 'ART HISTORY AND CRITICISM',
    value: 'ART HISTORY AND CRITICISM',
  },
  {
    id: 132,
    label: 'HISTORY',
    value: 'HISTORY',
  },
  {
    id: 133,
    label: 'UNITED STATES HISTORY',
    value: 'UNITED STATES HISTORY',
  },
  {
    id: 134,
    label: 'COSMETOLOGY SERVICES AND CULINARY ARTS',
    value: 'COSMETOLOGY SERVICES AND CULINARY ARTS',
  },
  {
    id: 135,
    label: 'FAMILY AND CONSUMER SCIENCES',
    value: 'FAMILY AND CONSUMER SCIENCES',
  },
  {
    id: 136,
    label: 'MILITARY TECHNOLOGIES',
    value: 'MILITARY TECHNOLOGIES',
  },
  {
    id: 137,
    label: 'PHYSICAL FITNESS PARKS RECREATION AND LEISURE',
    value: 'PHYSICAL FITNESS PARKS RECREATION AND LEISURE',
  },
  {
    id: 138,
    label: 'CONSTRUCTION SERVICES',
    value: 'CONSTRUCTION SERVICES',
  },
  {
    id: 139,
    label: 'ELECTRICAL',
    value: 'ELECTRICAL',
  },
  {
    id: 140,
    label: 'TRANSPORTATION SCIENCES AND TECHNOLOGIES',
    value: 'TRANSPORTATION SCIENCES AND TECHNOLOGIES',
  },
  {
    id: 141,
    label: 'MULTI/INTERDISCIPLINARY STUDIES',
    value: 'MULTI/INTERDISCIPLINARY STUDIES',
  },
  {
    id: 142,
    label: 'COURT REPORTING',
    value: 'COURT REPORTING',
  },
  {
    id: 143,
    label: 'PRE-LAW AND LEGAL STUDIES',
    value: 'PRE-LAW AND LEGAL STUDIES',
  },
  {
    id: 144,
    label: 'CRIMINAL JUSTICE AND FIRE PROTECTION',
    value: 'CRIMINAL JUSTICE AND FIRE PROTECTION',
  },
  {
    id: 145,
    label: 'PUBLIC ADMINISTRATION',
    value: 'PUBLIC ADMINISTRATION',
  },
  {
    id: 146,
    label: 'PUBLIC POLICY',
    value: 'PUBLIC POLICY',
  },
  {
    id: 148,
    label: 'PHYSICAL SCIENCES',
    value: 'PHYSICAL SCIENCES',
  },
  {
    id: 149,
    label: 'ASTRONOMY AND ASTROPHYSICS',
    value: 'ASTRONOMY AND ASTROPHYSICS',
  },
  {
    id: 150,
    label: 'ATMOSPHERIC SCIENCES AND METEOROLOGY',
    value: 'ATMOSPHERIC SCIENCES AND METEOROLOGY',
  },
  {
    id: 151,
    label: 'CHEMISTRY',
    value: 'CHEMISTRY',
  },
  {
    id: 152,
    label: 'GEOLOGY AND EARTH SCIENCE',
    value: 'GEOLOGY AND EARTH SCIENCE',
  },
  {
    id: 153,
    label: 'GEOSCIENCES',
    value: 'GEOSCIENCES',
  },
  {
    id: 154,
    label: 'OCEANOGRAPHY',
    value: 'OCEANOGRAPHY',
  },
  {
    id: 155,
    label: 'PHYSICS',
    value: 'PHYSICS',
  },
  {
    id: 156,
    label: 'MULTI-DISCIPLINARY OR GENERAL SCIENCE',
    value: 'MULTI-DISCIPLINARY OR GENERAL SCIENCE',
  },
  {
    id: 157,
    label: 'NUCLEAR',
    value: 'NUCLEAR',
  },
  {
    id: 158,
    label: 'PSYCHOLOGY',
    value: 'PSYCHOLOGY',
  },
  {
    id: 159,
    label: 'EDUCATIONAL PSYCHOLOGY',
    value: 'EDUCATIONAL PSYCHOLOGY',
  },
  {
    id: 160,
    label: 'CLINICAL PSYCHOLOGY',
    value: 'CLINICAL PSYCHOLOGY',
  },
  {
    id: 161,
    label: 'COUNSELING PSYCHOLOGY',
    value: 'COUNSELING PSYCHOLOGY',
  },
  {
    id: 162,
    label: 'INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY',
    value: 'INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY',
  },
  {
    id: 163,
    label: 'SOCIAL PSYCHOLOGY',
    value: 'SOCIAL PSYCHOLOGY',
  },
  {
    id: 164,
    label: 'MISCELLANEOUS PSYCHOLOGY',
    value: 'MISCELLANEOUS PSYCHOLOGY',
  },
  {
    id: 165,
    label: 'HUMAN SERVICES AND COMMUNITY ORGANIZATION',
    value: 'HUMAN SERVICES AND COMMUNITY ORGANIZATION',
  },
  {
    id: 166,
    label: 'SOCIAL WORK',
    value: 'SOCIAL WORK',
  },
  {
    id: 167,
    label: 'INTERDISCIPLINARY SOCIAL SCIENCES',
    value: 'INTERDISCIPLINARY SOCIAL SCIENCES',
  },
  {
    id: 168,
    label: 'GENERAL SOCIAL SCIENCES',
    value: 'GENERAL SOCIAL SCIENCES',
  },
  {
    id: 169,
    label: 'ECONOMICS',
    value: 'ECONOMICS',
  },
  {
    id: 170,
    label: 'CRIMINOLOGY',
    value: 'CRIMINOLOGY',
  },
  {
    id: 171,
    label: 'GEOGRAPHY',
    value: 'GEOGRAPHY',
  },
  {
    id: 172,
    label: 'INTERNATIONAL RELATIONS',
    value: 'INTERNATIONAL RELATIONS',
  },
  {
    id: 173,
    label: 'POLITICAL SCIENCE AND GOVERNMENT',
    value: 'POLITICAL SCIENCE AND GOVERNMENT',
  },
  {
    id: 174,
    label: 'SOCIOLOGY',
    value: 'SOCIOLOGY',
  },
  {
    id: 175,
    label: 'MISCELLANEOUS SOCIAL SCIENCES',
    value: 'MISCELLANEOUS SOCIAL SCIENCES',
  },
]
export const optionsLevel = [
  { id: 0, label: 'Secondary School', value: 'Secondary School' },
  { id: 1, label: 'Diploma', value: 'Diploma' },
  { id: 2, label: 'Adv Diplopa', value: 'Adv Diplopa' },
  { id: 3, label: 'Bachelor', value: 'Bachelor' },
  { id: 4, label: 'Master', value: 'Master' },
  { id: 5, label: 'Doctoral', value: 'Doctoral' },
]

export const optionsRelationship = [
  { id: 0, label: 'Husband', value: 'Husband' },
  { id: 1, label: 'Wife', value: 'Wife' },
  { id: 2, label: 'Father', value: 'Father' },
  { id: 3, label: 'Mother', value: 'Mother' },
  { id: 4, label: 'Brother', value: 'Brother' },
  { id: 5, label: 'Sister', value: 'Sister' },
  { id: 6, label: 'Child', value: 'Child' },
]

export const optionsDocumentType = [
  { id: 0, label: 'Academic Certificate (Ijazah)', value: 'Academic Certificate (Ijazah)' },
  { id: 1, label: 'Academic Record (Transkrip)', value: 'Academic Record (Transkrip)' },
  { id: 2, label: 'KTP', value: 'KTP' },
  { id: 2, label: 'SIM', value: 'SIM' },
  { id: 2, label: 'SIM A', value: 'SIM A' },
  { id: 2, label: 'SIM B1', value: 'SIM B1' },
  { id: 2, label: 'SIM B2', value: 'SIM B2' },
  { id: 2, label: 'SIM C', value: 'SIM C' },
  { id: 2, label: 'SIM D', value: 'SIM D' },
  { id: 2, label: 'BPJS Ketenagakerjaan', value: 'BPJS Ketenagakerjaan' },
  { id: 2, label: 'BPJS Kesehatan', value: 'BPJS Kesehatan' },
]

export const optionsSocialMedia = [
  { id: 0, label: 'Facebook', value: 'Facebook' },
  { id: 1, label: 'Instagram', value: 'Instagram' },
  { id: 2, label: 'Linkedin', value: 'Linkedin' },
  { id: 3, label: 'Telegram', value: 'Telegram' },
  { id: 4, label: 'TikTok', value: 'TikTok' },
  { id: 5, label: 'WhatsApp', value: 'WhatsApp' },
  { id: 6, label: 'X/Twitter', value: 'X/Twitter' },
  { id: 7, label: 'YouTube', value: 'YouTube' },
]