export { default as ICReload } from './fi-rr-refresh-black.svg'
export { default as ICField } from './field-list.svg'
export { default as ICUser } from './user-list.svg'
export { default as ICMenu } from './Ic_menu.svg'
export { default as ICClose } from './ic_close.svg'
export { default as ICCalendar } from './calendar.svg'
export { default as ICFinance } from './finance-group-logo.svg'
export { default as ICExclamation } from './exclamation.svg'
export { default as ICDownload } from './ic-download.svg'
export { default as ICUpload } from './ic-upload.svg'
export { default as ICSync } from './ic-sync.svg'
export { default as ICEyeCrossed } from './eye-crossed.svg'
export { default as ICInventory } from './ic-inventory.svg'
export { default as ICPurchaseOrg } from './ic-purchase-org.svg'
export { default as ICPlus } from './ic-plus.svg'
export { default as ICEdit } from './ic-edit.svg'
export { default as ICDelete } from './ic-delete.svg'
export { default as ICSave } from './ic-save.svg'
export { default as ICPlusWhite } from './ic-plus-white.svg'
export { default as ICCheckPrimary } from './check-as-primary.svg'
export { default as ICView } from './ic-view.svg'
export { default as ICDollar } from './dollar.svg'
export { default as ICManageCustGroupBuyingPrice } from './manage-cust-group-buying-price.svg'
export { default as IconAdd } from './ic-add.svg'
export { default as ICDollarBlack } from './ic-dollar-black.svg'
export { default as ICInfo } from './ic-info.svg'
export { default as ICCopy } from './ic-copy.svg'
export { default as ICPackage } from './ic-package.svg'
export { default as ICArrowRight } from './ic-arrow-right.svg'
export { default as ICArrowLeft } from './arrow-left.svg'
export { default as ICArrowAngleSmallDown } from './fi-sr-angle-small-down.svg'
export { default as ICFilter } from './ic_filter.svg'
export { default as ICGridMenu } from './grid-menu-icon.svg'
export { default as ICNewTab } from './ic_new tab.svg'
export { default as ICDownloadTemplate } from './download-template.svg'
export { default as ICUploadTemplate } from './upload-template.svg'
export { default as ICSyncData } from './sync-data.svg'
export { default as ExpandMinusIc } from './expand-icon-minus.svg'
export { default as ExpandPlusIc } from './expand-icon-plus.svg'
export { default as ExclamationBrownIc } from './exclamation-brown.svg'
export { default as ExclamationBlueIc } from './exclamation-blue.svg'
// export { default as ICLogo } from './favicon-eshop.ico'
export { default as ICLogo } from './favicon.ico'
export { default as ICDeliveryPackage } from './ic-delivery-package.svg'
export { default as ICDeliveryTruck } from './ic-delivery-truck.svg'
export { default as ICDoorDeliveryUntact } from './ic-door-delivery-untact.svg'
export { default as ICDoorDelivery } from './ic-door-delivery.svg'
export { default as ICPalletBox } from './ic-pallet-box.svg'
export { default as ICPlusRounded } from './ic_plus_rounded.svg'
export { default as ICRemove } from './ic-remove.svg'
export { default as ICShipCar } from './ic-shipment-car.svg'
export { default as ICShipHourglass } from './ic-shipment-hourglass.svg'
export { default as ICArrowDown } from './ic-arrow-down.svg'
export { default as ICArrowDownWhite } from './arrow-down-white.svg'
export { default as ICPaper } from './ic_single_paper.svg'
export { default as ICLayout } from './ic-layout-web.svg'
export { default as ICNoDate } from './ic-no-date.svg'
export { default as ICDownloadFile } from './download-file.svg'
export { default as ICUploadFile } from './upload-file.svg'
export { default as ICPlusBlue } from './ic-plus-blue.svg'
export { default as ICStarFull } from './ic-star-full.svg'
export { default as ICStarEmpty } from './ic-star-empty.svg'

export { default as ICCloses } from './ic-close.svg'
export { default as ICTruck } from './ic-truck.svg'
export { default as ICAddressBook } from './address-book.svg'
export { default as ICCompany } from './ic-building.svg'
export { default as ICTrashRed } from './ic-trash-red.svg'
export { default as ICExcelIcon } from './ic-excel-upload-icon.svg'
export { default as ICDocument } from './ic-document-thumbnail.svg'
export { default as ICRetry } from './fi-rr-refresh.svg'
export { default as ICSearch } from './fi-rr-search.svg'
export { default as ICWarn } from './monochrome.svg'

// Filter Icon
export { default as ICFilterAddFolder } from './Filter-addFolder.svg'
export { default as ICFilterEqual } from './Filter-equal.svg'
export { default as ICFilterGreaterEqual } from './Filter-greater-equal.svg'
export { default as ICFilterGreater } from './Filter-greater.svg'
export { default as ICFilterNotEqual } from './Filter-not-equal.svg'
export { default as ICFilterSelect } from './Filter-select.svg'
export { default as ICFilterLessEqual } from './Filter-smaller-equal.svg'
export { default as ICFilterLess } from './Filter-smaller.svg'

// Logistic Menu Filter
export { default as LogisticIcInventory } from './logistic-ic-inventory.svg'
export { default as LogisticIcGr } from './logistic-ic-gr.svg'
export { default as LogisticIcIntraBranch } from './logistic-ic-intra-plant.svg'
export { default as LogisticIcIntraChannel } from './logistic-ic-intra-channel.svg'
export { default as LogisticIcIntraSloc } from './logistic-ic-intra-sloc.svg'
export { default as LogisticIcCanvas } from './logistic-ic-canvas.svg'
export { default as LogisticIcBadStock } from './logistic-ic-bad-stock.svg'
export { default as LogisticIcSwapHandling } from './logistic-ic-swap-handling.svg'
export { default as LogisticIcStockAdjustment } from './logistic-ic-stock-adjustment.svg'
export { default as LogisticIcConfiguration } from './logistic-ic-configuration.svg'

// Marketin Menu
export { default as ICPromo } from './fi-megaphone.svg'

// HC - Dashboard
export { default as ICWaveHands } from './ic-wave-hands.svg'
export { default as ICAwardIMG } from './ic-hc-award.png'
export { default as ICLikeIMG } from './ic-hc-like.png'
export { default as ICTargetIMG } from './ic-hc-target.png'
export { default as ICTeamIMG } from './ic-hc-team.png'
export { default as ICHandShakeIMG } from './ic-hc-handshake.png'

// HC - organization development
export { default as ICNetworkingIMG } from './ic-hc-networking-perspective.png'
export { default as ICUserIMG } from './ic-hc-user-perspective.png'
export { default as ICMagnifierIMG } from './ic-hc-magnifier-perspective.png'
export { default as ICDashboardIMG } from './ic-hc-dashboard-perspective.png'
export { default as ICChartIMG } from './ic-hc-chart-perspective.png'
export { default as ICStarIMG } from './ic-hc-star-perspective.png'
export { default as ICComputerIMG } from './ic-hc-computer-perspective.png'
export { default as ICMobileIMG } from './ic-hc-mobile-app-perspective.png'
export { default as ICBookPerspective } from './ic-hc-books_perspective_matte.png'
export { default as ICJobTitle } from './ic-hc-job-title.svg'
export { default as ICDate } from './ic-hc-date.svg'
export { default as ICReportPerson } from './ic-hc-report-person.svg'
export { default as ICCardPosition } from './ic-hc-card-position.svg'
export { default as ICCostCenter } from './ic-hc-cost-center.svg'
export { default as ICLengthOfService } from './ic-hc-document-1.svg'
export { default as ICStarLink } from './ic-hc-starlink.svg'
export { default as ICLegalEntity } from './ic-hc-legal-entity.svg'
export { default as ICDocumentReport } from './ic-hc-document-report.svg'
export { default as ICAtom } from './ic-hc-atom.svg'
export { default as ICPlacementLocation } from './ic-hc-location-placement.svg'
export { default as ICCrown } from './ic-hc-crown.svg'
export { default as ICEmail } from './ic-hc-email.svg'
export { default as ICLinkedIn } from './ic-hc-linkedin.svg'
export { default as ICUniversity } from './ic-hc-university.svg'
export { default as ICAngleSmallRight } from './fi-rr-angle-small-right.svg'
export { default as ICAngleSmallRightWhite } from './fi-rr-angle-small-right-white.svg'
export { default as ICAngleSmallLeft } from './fi-rr-angle-small-left.svg'
export { default as ICHCBuilding } from './ic-hc-building.png'
export { default as ICHCComputer } from './ic-hc-computer.png'
export { default as ICHCFlag } from './ic-hc-flag.png'
export { default as ICHCOfficeBag } from './ic-hc-office-bag.png'
export { default as ICHCPuzzle } from './ic-hc-puzzle.png'
export { default as ICHCAddApp } from './ic-hc-add-app.png'
export { default as ICHCBankBuilding } from './ic-hc-bank-building.png'
export { default as ICHCBiodata } from './ic-hc-biodata.png'
export { default as ICHCNotebook } from './ic-hc-notebook.png'
export { default as ICHCWorld } from './ic-hc-world.png'
export { default as ICHCArrowDownBlue } from './ic-arrow-down-blue.svg'
export { default as ICHCUploadTemplate } from './ic-hc-upload-template.svg'
export { default as ICHCDownloadTemplate } from './ic-hc-download-template.svg'
export { default as ICHCFileXLSX } from './ic-hc-file-xlsx.svg'
export { default as ICHCFingerprint } from './ic-hc-fingerprint.png'
export { default as ICHCAvatar } from './ic-hc-avatar.png'
export { default as ICHCPicture } from './fi-rr-picture.svg'
export { default as ICHCShirt } from './ic-hc-shirt.png'
export { default as ICHCPants } from './ic-hc-pants.png'
export { default as ICHCShoes } from './ic-hc-shoes.png'

// HC - OD / Detail / Emergency Contact
export { default as ICEmergencyContactName } from './ic-hc-emergency-contact-name.svg'
export { default as ICEmergencyContactNumber } from './ic-hc-emergency-contact-number.svg'
export { default as ICRelationship } from './ic-hc-relationship.svg'
export { default as ICContactAddress } from './ic-hc-contact-address.svg'

// HC-Performance Management
export { default as ICHCPerspectiveMatte } from './ic-hc-perspective-matte.png'
export { default as ICHCPerspectiveResult } from './ic-hc-perspective-result.png'
export { default as ICHCPerspectiveMonitoring } from './ic-hc-monitoring-chart.png'
export { default as ICHCKPIFolder } from './ic-hc-kpi-folder.png'
export { default as ICHCKPITarget } from './ic-hc-performance-target.png'
export { default as ICHCKStarPerspectiveMatte } from './ic-hc-star-perspective-matte.png'
