export const tagColors = {
  purple: ['Delivery'],
  green: [
    'Done',
    'Complete',
    'Available',
    'Routing Complete',
    'PGI Done',
    'In Stock',
    'Generate',
    'Visited',
    'Ontime',
    'CLOSE',
    'PAID',
    'Billing Created',
    'PGI Complete',
    'Delivery Order',
    'Active',
  ],
  geekblue: ['SAP SO Complete'],
  red: [
    'Out of Stock',
    'Canceled',
    'Cancel',
    'Rejected',
    'Cancelled',
    'Undelivered',
    'Unvisited',
    'Overdue',
    'PENDING',
    'Incomplete',
    'PGI Failed',
  ],
  blue: ['Approved', 'SAP SO Complete', 'Partial Collection', 'Partial Paid', 'UNPAID', 'Sales Order'],
  orange: ['Open', 'Delivery STO"'],
  yellow: [
    'Delivery STO',
    // 'Draft',
    'Wait For Approval',
    'Waiting For Approval',
    'Pending',
    'Reservation',
    'Skip',
    'INVOICE SENT',
    'PARTIALLY COLLECTED',
    'FULLY COLLECTED',
    'IN PROGRESS',
    'PARTIAL PAID',
    'Billing Process',
    'Partial',
  ],
}

export const tagColorsV2 = {
  green: [
    'Approved',
    'Complete',
  ],
  greenlighter: [
    'Checkout Success',
    'Sesuai',
    'sesuai',
  ],
  pink: [
    'Unloading',
  ],
  red: [
    'Cancelled',
    'Rejected',
  ],
  yellow: [
    'Waiting Approval',
  ],
  waferblue: [
    'On Delivery',
    'Tambahan',
    'tambahan',
  ],
  cheese: [
    'Waiting Check Out',
    'Waiting Unloading',
    'Kurang',
    'kurang',
  ],
  gogumapurple: [
    'Waiting Approval GR',
  ],
  black: [],
  greycheese: [],
}
