import Head from 'next/head'
import React, { ReactNode, PropsWithChildren } from 'react'
import { ICLogo } from 'src/assets'

export default function LoginLayout(props: PropsWithChildren<{}>) {
  const { children } = props

  return (
    <>
      <Head>
        <title>EDS - Login</title>
        <meta name="description" content="Generated by EDS" />
        <link rel="icon" href={ICLogo.src} />
      </Head>
      <div
        style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}
      >
        {children}
      </div>
    </>
  )
}
