export const sideBarMenu = [
  {
    id: 2,
    index: 1,
    group: 2,
    name: 'Master Data Management',
    key: 'mdm',
    children: [
      {
        type: 'title',
        title: 'Inventory',
        icon: '',
        index: 0,
      },
      {
        type: 'submodule',
        title: 'Product',
        icon: 'fi-rr-box',
        index: 1,
        menus: [
          {
            type: 'menu',
            title: 'Product',
            screen: 'mdm.product',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Product Category',
            screen: 'mdm.product.category',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Product Variant',
            screen: 'mdm.product.variant',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Product Option',
            screen: 'mdm.product.option',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Product Brand',
            screen: 'mdm.product.brand',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Product Group',
            screen: 'mdm.product.group',
            index: 5,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Vendor',
        icon: 'fi-rr-package',
        index: 2,
        menus: [
          {
            type: 'menu',
            title: 'Vendor',
            screen: 'mdm.vendor',
            index: 0,
          },
        ],
      },
      {
        type: 'title',
        title: 'Sales',
        icon: '',
        index: 3,
      },
      {
        type: 'submodule',
        title: 'Pricing',
        icon: 'fi-rr-dollar',
        index: 4,
        menus: [
          {
            type: 'menu',
            title: 'Pricing Structure',
            screen: 'mdm.pricing.structure',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Retail Pricing',
            screen: 'mdm.retail.pricing',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Customer',
        icon: 'fi-rr-user',
        index: 5,
        menus: [
          {
            type: 'menu',
            title: 'Customer',
            screen: 'mdm.customer',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Customer Group',
            screen: 'mdm.customer.group',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Salesman',
        icon: 'fi-rr-man-head',
        index: 6,
        menus: [
          {
            type: 'menu',
            title: 'Salesman',
            screen: 'mdm.salesman',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Sales Division',
            screen: 'mdm.sales.division',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Salesman Group',
            screen: 'mdm.salesman.group',
            index: 2,
          },
        ],
      },
      {
        type: 'title',
        title: 'Finance',
        icon: '',
        index: 7,
      },
      {
        type: 'submodule',
        title: 'Term of Payment',
        icon: 'fi-rr-document-signed',
        index: 8,
        menus: [
          {
            type: 'menu',
            title: 'Term Of Payment',
            screen: 'mdm.term.of.payment',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Tax',
        icon: 'fi-rr-diploma',
        index: 9,
        menus: [
          {
            type: 'menu',
            title: 'Tax',
            screen: 'mdm.tax',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Profit Center',
        icon: 'fi-rr-money',
        index: 10,
        menus: [
          {
            type: 'menu',
            title: 'Profit Center',
            screen: 'mdm.profit.center',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Cost Center',
        icon: 'fi-rr-dollar',
        index: 11,
        menus: [
          {
            type: 'menu',
            title: 'Cost Center',
            screen: 'mdm.cost.center',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'G/L & Bank Account',
        icon: 'fi-rr-bank',
        index: 12,
        menus: [
          {
            type: 'menu',
            title: 'GL Account',
            screen: 'mdm.gl.account',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Bank Account',
            screen: 'mdm.bank.account',
            index: 1,
          },
        ],
      },
      {
        type: 'title',
        title: 'Logistic',
        icon: '',
        index: 13,
      },
      {
        type: 'submodule',
        title: 'Transportation Group',
        icon: 'fi-rr-truck-side',
        index: 14,
        menus: [
          {
            type: 'menu',
            title: 'Transportation Group',
            screen: 'mdm.transportation.group',
            index: 0,
          },
        ],
      },
      {
        type: 'title',
        title: 'Human Capital',
        icon: '',
        index: 15,
      },
      {
        type: 'submodule',
        title: 'Employee',
        icon: 'fi-rr-id-badge',
        index: 16,
        menus: [
          {
            type: 'menu',
            title: 'Employee List',
            screen: 'mdm.employee.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Job Position',
            screen: 'mdm.job.position',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Job Level',
            screen: 'mdm.job.level',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Training Type',
            screen: 'mdm.training.type',
            index: 3,
          },
        ],
      },
      {
        type: 'title',
        title: 'General',
        icon: '',
        index: 17,
      },
      {
        type: 'submodule',
        title: 'Country Structure',
        icon: 'fi-rr-world',
        index: 18,
        menus: [
          {
            type: 'menu',
            title: 'Country',
            screen: 'mdm.country',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Postal Code',
            screen: 'mdm.postal.code',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Currency',
            screen: 'mdm.currency',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Exchange Rate',
            screen: 'mdm.exchange.rate',
            index: 3,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Company Structure',
        icon: 'fi-rr-building',
        index: 19,
        menus: [
          {
            type: 'menu',
            title: 'Channel',
            screen: 'mdm.channel',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Branch',
            screen: 'mdm.branch',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Sales Organization',
            screen: 'mdm.sales.organization',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Purchase Organization',
            screen: 'mdm.purchase.organization',
            index: 3,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Working Calendar',
        icon: 'fi-rr-calendar',
        index: 20,
        menus: [
          {
            type: 'menu',
            title: 'Working Calendar',
            screen: 'mdm.working.calendar',
            index: 0,
          },
        ],
      },
    ],
  },
  {
    id: 1,
    index: 0,
    group: 1,
    name: 'Config',
    key: 'conf',
    children: [
      {
        type: 'title',
        title: 'Report',
        icon: '',
        index: 0,
      },
      {
        type: 'submodule',
        title: 'User Log',
        icon: 'fi-rr-stats',
        index: 1,
        menus: [
          {
            type: 'menu',
            title: 'User Logs',
            screen: 'conf.user.logs',
            index: 0,
          },
        ],
      },
      {
        type: 'title',
        title: 'Configuration',
        icon: '',
        index: 2,
      },
      {
        type: 'submodule',
        title: 'Billing',
        icon: 'fi-rr-document-signed',
        index: 3,
        menus: [
          {
            type: 'menu',
            title: 'Payment',
            screen: 'conf.billing.payment',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Calculation',
            screen: 'calculation',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Company List',
        icon: 'fi-rr-building',
        index: 4,
        menus: [
          {
            type: 'menu',
            title: 'Company List',
            screen: 'mdm.company',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'User Config',
        icon: 'fi-rr-user',
        index: 5,
        menus: [
          {
            type: 'menu',
            title: 'User List',
            screen: 'mdm.user.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Role List',
            screen: 'mdm.role.list',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Permission List',
            screen: 'mdm.permission.list',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Approval List',
            screen: 'mdm.approval.list',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Sequence Number',
            screen: 'mdm.sequence.number',
            index: 4,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Bussiness Process',
        icon: 'fi-rr-vector',
        index: 6,
        menus: [
          {
            type: 'menu',
            title: 'Process',
            screen: 'mdm.process',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Business Process',
            screen: 'mdm.business.process',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Menu Config',
        icon: 'fi-rr-grid',
        index: 7,
        menus: [
          {
            type: 'menu',
            title: 'Menu List',
            screen: 'mdm.menu.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Menu Design',
            screen: 'mdm.menu.design',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Module Config',
        icon: 'fi-rr-id-badge',
        index: 8,
        menus: [
          {
            type: 'menu',
            title: 'Module Config',
            screen: 'mdm.module.config',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Finance Config',
        icon: 'fi-rr-calculator',
        index: 9,
        menus: [
          {
            type: 'menu',
            title: 'Coa Template',
            screen: 'mdm.coa.template',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Account Group',
            screen: 'mdm.account.group',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Formating',
        icon: 'fi-rr-calendar',
        index: 10,
        menus: [
          {
            type: 'menu',
            title: 'Number Format',
            screen: 'mdm.number.format',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Date Format',
            screen: 'mdm.date.format',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Currency Format',
            screen: 'mdm.currency.format',
            index: 2,
          },
        ],
      },
    ],
  },
  {
    id: 8,
    index: 5,
    group: 8,
    name: 'Marketing',
    key: 'mkt',
    children: [
      {
        type: 'submodule',
        title: 'Marketing',
        icon: '',
        index: 0,
        menus: [
          {
            type: 'menu',
            title: 'User Logs',
            screen: 'conf.user.logs',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Create New Promotion',
            screen: 'mkt.new_promotion',
            index: 1,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    index: 3,
    group: 5,
    name: 'Logistic',
    key: 'log',
    children: [
      {
        type: 'title',
        title: 'Logistic',
        icon: '',
        index: 1,
      },
      {
        type: 'submodule',
        title: 'Inventory',
        icon: 'fi-rr-cube',
        index: 2,
        menus: [
          {
            type: 'menu',
            title: 'Stock Realtime',
            screen: 'log.inv.stock',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Availability',
            screen: 'log.inv.availability',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Material In Transit',
            screen: 'log.inv.material_in_transit',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Material Document',
            screen: 'log.inv.material_document',
            index: 3,
          },
          {
            type: 'menu',
            title: 'WH Stock Mutation',
            screen: 'log.inv.whstock',
            index: 4,
          },
        ],
      },
      {
        type: 'submodule',
        title: ' GR From Principal',
        icon: 'fi-rr-shuffle',
        index: 3,
        menus: [
          {
            type: 'menu',
            title: 'GR Principal',
            screen: 'log.grprcp.good_receipt',
            index: 0,
          },
          {
            type: 'menu',
            title: 'GReturn Principal',
            screen: 'log.grprcp.good_return',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Intra Branch',
        icon: 'fi-rr-chart-tree',
        index: 4,
        menus: [
          {
            type: 'menu',
            title: 'PO STO',
            screen: 'log.intra_branch.posto',
            index: 0,
          },
          {
            type: 'menu',
            title: 'DO STO',
            screen: 'log.intra_branch.do_sto',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Approval',
            screen: 'log.intra_branch.approval',
            index: 2,
          },
          {
            type: 'menu',
            title: 'GI Intra Branch',
            screen: 'log.intra_branch.good_issue',
            index: 3,
          },
          {
            type: 'menu',
            title: 'GR Intra Branch',
            screen: 'log.intra_branch.good_receipt',
            index: 4,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Intra Frozen',
        icon: 'fi-rr-data-transfer',
        index: 5,
        menus: [
          {
            type: 'menu',
            title: 'Request Intra Frozen',
            screen: 'log.intra_frozen',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Approval Intra Frozen',
            screen: 'log.intra_frozen.approval',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Material  Intra Frozen',
            screen: 'log.intra_frozen.material',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Intra Sloc',
        icon: 'fi-rr-layout-fluid',
        index: 6,
        menus: [
          {
            type: 'menu',
            title: 'Request',
            screen: 'log.intra_sloc.request',
            index: 0,
          },
          {
            type: 'menu',
            title: 'GI Intra Sloc',
            screen: 'log.intra_sloc.good_issue',
            index: 1,
          },
          {
            type: 'menu',
            title: 'GR Intra Sloc',
            screen: 'log.intra_sloc.good_receipt',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Canvas',
        icon: 'fi-rr-ambulance',
        index: 7,
        menus: [
          {
            type: 'menu',
            title: 'Stock Reservation',
            screen: 'log.canvas.reservation',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Approval',
            screen: 'log.canvas.approval',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Transfer To GS',
            screen: 'log.canvas.transfer_to_gs',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Disposal',
        icon: 'fi-rr-broom',
        index: 8,
        menus: [
          {
            type: 'menu',
            title: 'Disposal',
            screen: 'log.bad_stock.disposal',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Swap Handling',
        icon: 'fi-rr-data-transfer',
        index: 9,
        menus: [
          {
            type: 'menu',
            title: 'List Swap Handling',
            screen: 'log.inv.swap_handling',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Swap Handling',
            screen: 'log.swap_handling',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Stock',
        icon: '',
        index: 10,
        menus: [
          {
            type: 'menu',
            title: 'Stock Opname',
            screen: 'log.stock.opname',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Approval Stock Opname',
            screen: 'log.stock.approval',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Stock Adjustment',
            screen: 'log.stock.adjustment',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Approval Stock Adjustment',
            screen: 'log.stock.approval_adjust',
            index: 3,
          },
        ],
      },
      {
        type: 'title',
        title: 'General',
        icon: '',
        index: 11,
      },
      {
        type: 'submodule',
        title: 'Configuration',
        icon: 'fi-rr-settings',
        index: 12,
        menus: [
          {
            type: 'menu',
            title: 'Company',
            screen: 'log.config.company',
            index: 0,
          },
          {
            type: 'menu',
            title: 'GR Auto Return',
            screen: 'log.config.gr_auto_return',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Sloc',
            screen: 'log.config.sloc',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Sloc Company',
            screen: 'log.config.sloc_company',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Sloc Customer Group',
            screen: 'log.config.sloc_cust_group',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Sloc Salesman',
            screen: 'log.config.sloc_salesman',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Order Type To Sloc',
            screen: 'log.config.order_type_to_sloc',
            index: 6,
          },
          {
            type: 'menu',
            title: 'Item Category',
            screen: 'log.config.item_category',
            index: 7,
          },
          {
            type: 'menu',
            title: 'Branch Location',
            screen: 'log.config.branch_location',
            index: 8,
          },
          {
            type: 'menu',
            title: 'Mapping Product Intra',
            screen: 'log.config.mapping_intra',
            index: 9,
          },
        ],
      },
      {
        type: 'title',
        title: 'PMA Receiving',
        icon: '',
        index: 13,
      },
      {
        type: 'submodule',
        title: 'Dashboard',
        icon: 'fi-rr-dashboard-1',
        index: 14,
        menus: [
          {
            type: 'menu',
            title: 'Analytical',
            screen: 'log.mot.analytical',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Transactional',
            screen: 'log.monitoring',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Delivery Schedule',
            screen: 'log.mon.delivery_schedule',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Monitoring',
        icon: 'fi-rr-screen',
        index: 15,
        menus: [
          {
            type: 'menu',
            title: 'Monitoring (R)',
            screen: 'log.monitoring.list',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Master Data',
        icon: 'fi-rr-database',
        index: 16,
        menus: [
          {
            type: 'menu',
            title: 'Mapping Branch (R)',
            screen: 'log.mapping.branch',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Region Management',
            screen: 'log.region.management',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Backlog Category',
            screen: 'log.backlog.category',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Integration Log',
        icon: 'fi-rr-vector',
        index: 17,
        menus: [
          {
            type: 'menu',
            title: 'Shipment (SAP)',
            screen: 'log.integration.shipment',
            index: 0,
          },
          {
            type: 'menu',
            title: 'GR (e-BASP)',
            screen: 'log.integration.grebasp',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Config',
        icon: 'fi-rr-settings-sliders',
        index: 18,
        menus: [
          {
            type: 'menu',
            title: 'Scheduler',
            screen: 'log.config.sheduler',
            index: 0,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    index: 6,
    group: 6,
    name: 'Procurement',
    key: 'proc',
    children: [
      {
        type: 'title',
        title: 'Procurement',
        icon: '',
        index: 0,
      },
      {
        type: 'submodule',
        title: 'Transaction',
        icon: 'fi-rr-screen',
        index: 1,
        menus: [
          {
            type: 'menu',
            title: 'Good Receipt',
            screen: 'epro.good.receipt',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Purchase Order',
            screen: 'epro.purchase.order',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Purchasing Group',
            screen: 'epro.purchasing.group',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Master Data',
        icon: 'fi-rr-align-justify',
        index: 2,
        menus: [
          {
            type: 'menu',
            title: 'Purchasing Org',
            screen: 'epro.purchasing.org',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Purchasing Type',
            screen: 'epro.purchasing.type',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Configuration',
        icon: 'fi-rr-makeup-brush',
        index: 3,
        menus: [
          {
            type: 'menu',
            title: 'Field (Procurement)',
            screen: 'epro.field',
            index: 0,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    index: 4,
    group: 3,
    name: 'Finance',
    key: 'fico',
    children: [
      {
        type: 'title',
        title: 'Report Finance & Accounting',
        icon: '',
        index: 0,
      },
      {
        type: 'submodule',
        title: 'Report',
        icon: 'fi-rr-database',
        index: 1,
        menus: [
          {
            type: 'menu',
            title: 'Report Profit or Loss',
            screen: 'fico.report.profit.loss',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Report Balance Sheet',
            screen: 'fico.report.balance.sheet',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Report Ledger',
            screen: 'fico.report.ledger',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Report Budget VS Actual',
            screen: 'fico.report.budget.actual',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Lapping',
            screen: 'fico.report.lapping',
            index: 6,
          },
          {
            type: 'menu',
            title: 'Upload Statement',
            screen: 'fico.cash.bank.statement',
            index: 7,
          },
        ],
      },
      {
        type: 'title',
        title: 'Transaction',
        icon: '',
        index: 2,
      },
      {
        type: 'submodule',
        title: 'Accounting',
        icon: 'fi-rr-book-alt',
        index: 3,
        menus: [
          {
            type: 'menu',
            title: 'Accounting General Journal',
            screen: 'fico.general.journal',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Accounting Reversal Journal',
            screen: 'fico.reversal.journal',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Accounting Accrual Journal',
            screen: 'fico.accrual.journal',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Budget',
        icon: 'fi-rr-dollar',
        index: 4,
        menus: [
          {
            type: 'menu',
            title: 'Budget List',
            screen: 'fico.budget.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Budget Transfer',
            screen: 'fico.transfer',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Budget Supplement or Return',
            screen: 'fico.supplement.or.return',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Asset',
        icon: 'fi-rr-car',
        index: 5,
        menus: [
          {
            type: 'menu',
            title: 'Asset Opname',
            screen: 'fico.opname',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Asset List',
            screen: 'fico.asset.list',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Asset Mutation',
            screen: 'fico.asset.mutation',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Asset GR Mutation',
            screen: 'fico.gr.mutation',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Asset Disposal',
            screen: 'fico.asset.disposal',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Asset Adjusment Value',
            screen: 'fico.asset.adjusment',
            index: 5,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Cash & Bank',
        icon: 'fi-rr-bank',
        index: 6,
        menus: [
          {
            type: 'menu',
            title: 'Cash & Bank List',
            screen: 'fico.cash.bank.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Cash & Bank Cash Advances',
            screen: 'fico.cash.bank.advances',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Cash & Bank Cash Advances Realization',
            screen: 'fico.cash.bank.realization',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Promotion List',
            screen: 'mkt.promotion_list',
            index: 3,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Account Receivable',
        icon: 'fi-rr-money',
        index: 7,
        menus: [
          {
            type: 'menu',
            title: 'Account Receivable List',
            screen: 'fico.ar.receivable',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Account Receivable Cek / Giro',
            screen: 'fico.ar.cek.giro',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Account Receivable Down Payment',
            screen: 'fico.ar.down.payment',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Account Payable',
        icon: 'fi-rr-credit-card',
        index: 8,
        menus: [
          {
            type: 'menu',
            title: 'Account Payable Down Payment',
            screen: 'fico.ap.down.payment',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Account Payable Vendor Invoicing',
            screen: 'fico.ap.vendor.invoicing',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Cash & Bank Payment Advice',
            screen: 'fico.cash.bank.advice',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Account Payable Purchasing Verification',
            screen: 'fico.ap.purchasing.verification',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Tax Verification',
            screen: 'fico.tax.verification',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Account Payable Accounting Post',
            screen: 'fico.ap.accounting.post',
            index: 5,
          },
        ],
      },
      {
        type: 'title',
        title: 'Master Data & Config',
        icon: '',
        index: 9,
      },
      {
        type: 'submodule',
        title: 'Master Data & Config',
        icon: 'fi-rr-data-transfer',
        index: 10,
        menus: [
          {
            type: 'menu',
            title: 'Master Data Account Group',
            screen: 'fico.master.account.group',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Master Data Advances Type',
            screen: 'fico.master.advances.type',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Master Data Controlling Area',
            screen: 'fico.master.controlling.area',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Master Data Depreciation Area',
            screen: 'fico.master.depreciation.area',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Master Data Depreciation Key',
            screen: 'fico.master.depreciation.key',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Master Data Document Type',
            screen: 'fico.master.doc.type',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Master Data Field Group',
            screen: 'fico.master.field.group',
            index: 6,
          },
          {
            type: 'menu',
            title: 'Master Data Number Range',
            screen: 'fico.master.number.range',
            index: 7,
          },
          {
            type: 'menu',
            title: 'Master Data Order Type',
            screen: 'fico.master.order.type',
            index: 8,
          },
          {
            type: 'menu',
            title: 'Master Data Processing Group',
            screen: 'fico.master.processing.group',
            index: 9,
          },
        ],
      },
    ],
  },
  {
    id: 23,
    index: 8,
    group: 23,
    icon: 'fi-rr-life-ring',
    name: 'HC',
    key: 'hc',
    children: [
      {
        type: 'title',
        title: 'OVERVIEW',
        icon: '',
        index: 2,
      },
      {
        type: 'submodule',
        title: 'Dashboard',
        icon: 'fi-rr-dashboard',
        index: 0,
        menus: [
          {
            type: 'menu',
            title: 'Dashboard',
            screen: 'hc.dashboard',
            index: 0,
          },
        ],
      },
      {
        type: 'title',
        title: '_________________________________',
        icon: '',
        index: 1,
      },
      {
        type: 'title',
        title: 'Menu',
        icon: '',
        index: 2,
      },
      {
        type: 'submodule',
        title: 'Menu',
        icon: 'fi-rr-comment-user',
        index: 3,
        menus: [
          {
            type: 'menu',
            title: 'Employee Self Services',
            screen: 'hc.employee.self.services',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Menu',
        icon: 'fi-rr-layers',
        index: 22,
        menus: [
          {
            type: 'menu',
            title: 'Master Data',
            screen: 'hc.master.data',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Menu',
        icon: 'fi-rr-develop',
        index: 22,
        menus: [
          {
            type: 'menu',
            title: 'Org. Development',
            screen: 'hc.organization.development',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Menu',
        icon: 'fi-rr-chart-tree',
        index: 22,
        menus: [
          {
            type: 'menu',
            title: 'Performance Mgt.',
            screen: 'hc.performance.management',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Menu',
        icon: 'fi-rr-dashboard',
        index: 22,
        menus: [
          {
            type: 'menu',
            title: 'Table',
            screen: 'hc.table',
            index: 1,
          },
        ],
      },
    ],
  },
  {
    id: 17,
    index: 7,
    group: 17,
    name: 'VIM',
    key: 'vim',
    children: [
      {
        type: 'title',
        title: 'VENDOR INVOICING MANAGEMENT',
        icon: '',
        index: 0,
      },
      {
        type: 'submodule',
        title: 'Vendor Menu',
        icon: '',
        index: 1,
        menus: [
          {
            type: 'menu',
            title: 'Detail Toko',
            screen: 'sfa.to.detail_store',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Invoice',
            screen: 'vim.invoice.list',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'User Menu',
        icon: '',
        index: 2,
        menus: [
          {
            type: 'menu',
            title: 'Vendor Invoicing',
            screen: 'vim.vendor.invoicing.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Logisitic Verification',
            screen: 'vim.logistic.verification.list',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Shipment Verification',
            screen: 'vim.shipment.verification.list',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Distribution Center Verification',
            screen: 'vim.dc.verification.list',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Customer Service Verification',
            screen: 'vim.cs.verification.list',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Purchase Verification',
            screen: 'vim.purchase.verification.list',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Accounting Verification',
            screen: 'vim.accounting.verif.list',
            index: 6,
          },
          {
            type: 'menu',
            title: 'Tax Verification VIM',
            screen: 'vim.tax.verification.list',
            index: 7,
          },
          {
            type: 'menu',
            title: 'Payment VIM',
            screen: 'vim.payment.list',
            index: 8,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Master Data',
        icon: '',
        index: 3,
        menus: [
          {
            type: 'menu',
            title: 'Requirement',
            screen: 'vim.master.requirement',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Vendor Requirement',
            screen: 'vim.master.vendor.requirement',
            index: 1,
          },
          {
            type: 'menu',
            title: 'PPn',
            screen: 'vim.master.ppn',
            index: 2,
          },
          {
            type: 'menu',
            title: 'PPh ID',
            screen: 'vim.master.pph.id',
            index: 3,
          },
          {
            type: 'menu',
            title: 'PPh',
            screen: 'vim.master.pph',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Special GL',
            screen: 'vim.master.special.gl',
            index: 5,
          },
          {
            type: 'menu',
            title: 'GL Account VIM',
            screen: 'vim.master.gl.account',
            index: 6,
          },
          {
            type: 'menu',
            title: 'Cost Center VIM',
            screen: 'vim.master.cost.center',
            index: 7,
          },
          {
            type: 'menu',
            title: 'Currency VIM',
            screen: 'vim.master.currency',
            index: 8,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    index: 2,
    group: 4,
    name: 'Sales',
    key: 'sls',
    children: [
      {
        type: 'submodule',
        title: 'Dashboard',
        icon: 'fi-rr-stats',
        index: 0,
        menus: [
          {
            type: 'menu',
            title: 'Dashboard Sales',
            screen: 'sls.dashboard',
            index: 0,
          },
        ],
      },
      {
        type: 'title',
        title: 'ORDER TO CASH',
        icon: '',
        index: 1,
      },
      {
        type: 'submodule',
        title: 'Quotation',
        icon: 'fi-rr-shopping-cart-add',
        index: 2,
        menus: [
          {
            type: 'menu',
            title: 'Take a Return',
            screen: 'sls.otc.take_return',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Quotation',
            screen: 'sls.otc.quotation',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: ' Sales Order',
        icon: 'fi-rr-shopping-cart-check',
        index: 3,
        menus: [
          {
            type: 'menu',
            title: 'Sales Order',
            screen: 'sls.otc.sales_order',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Summary Order',
            screen: 'sls.otc.summary_order',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: ' Delivery Order',
        icon: 'fi-rr-ambulance',
        index: 4,
        menus: [
          {
            type: 'menu',
            title: 'Delivery Order',
            screen: 'sls.otc.delivery_order',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Shipment',
        icon: 'fi-rr-school-bus',
        index: 5,
        menus: [
          {
            type: 'menu',
            title: 'Shipment',
            screen: 'sls.otc.shipment',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Proforma Invoice',
            screen: 'sls.otc.proforman_invoice',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Billing',
        icon: 'fi-rr-dollar',
        index: 6,
        menus: [
          {
            type: 'menu',
            title: 'Billing',
            screen: 'sls.otc.billing',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Collection',
        icon: 'fi-rr-list-check',
        index: 7,
        menus: [
          {
            type: 'menu',
            title: 'Collection',
            screen: 'sls.otc.collection',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Undelivery',
        icon: 'fi-rr-car',
        index: 8,
        menus: [
          {
            type: 'menu',
            title: 'Undelivery',
            screen: 'sls.otc.undelivery',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Approval',
        icon: 'fi-rr-checkbox',
        index: 9,
        menus: [
          {
            type: 'menu',
            title: 'Approval SO',
            screen: 'sls.otc.approval',
            index: 0,
          },
        ],
      },
      {
        type: 'title',
        title: 'Master Data',
        icon: '',
        index: 10,
      },
      {
        type: 'submodule',
        title: 'Base Master',
        icon: 'fi-rr-settings',
        index: 11,
        menus: [
          {
            type: 'menu',
            title: 'Users',
            screen: 'sls.mst.user',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Sales Organization',
            screen: 'sap.sls.mst.sales_org',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Sales Office',
            screen: 'sap.sls.mst.sales_office',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Sales Group',
            screen: 'sap.sls.mst.sales_group',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Channel',
            screen: 'sap.sls.mst.channel',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Customer Group',
            screen: 'sap.sls.mst.customer_group',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Customer Group 1',
            screen: 'sap.sls.mst.customer_group1',
            index: 6,
          },
          {
            type: 'menu',
            title: 'Customer Group 2',
            screen: 'sap.sls.mst.customer_group2',
            index: 7,
          },
          {
            type: 'menu',
            title: 'Customer Group 3',
            screen: 'sap.sls.mst.customer_group3',
            index: 8,
          },
          {
            type: 'menu',
            title: 'Region',
            screen: 'sap.sls.mst.region',
            index: 9,
          },
          {
            type: 'menu',
            title: 'City',
            screen: 'sap.sls.mst.city',
            index: 10,
          },
          {
            type: 'menu',
            title: 'District',
            screen: 'sap.sls.mst.district',
            index: 11,
          },
          {
            type: 'menu',
            title: 'Term of Payment',
            screen: 'sap.sls.mst.term_of_payment',
            index: 12,
          },
          {
            type: 'menu',
            title: 'Branch',
            screen: 'sap.sls.mst.branch',
            index: 13,
          },
          {
            type: 'menu',
            title: 'Price List',
            screen: 'sap.sls.mst.price_list',
            index: 14,
          },
          {
            type: 'menu',
            title: 'Currency EDS',
            screen: 'sap.sls.mst.currency',
            index: 15,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Customer',
        icon: 'fi-rr-following',
        index: 12,
        menus: [
          {
            type: 'menu',
            title: 'Customer ',
            screen: 'sls.mst.customer',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Customer NOO',
            screen: 'sls.mst.customer_noo',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Approval NOO',
            screen: 'sls.mst.approval_noo',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Credit Limit',
            screen: 'sls.config.credit_limit',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Credit Limit Approval',
            screen: 'sls.config.credit_limit_approval',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Rules',
            screen: 'sap.sls.mst.rules',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Check Rule',
            screen: 'sap.sls.mst.check_rule',
            index: 6,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Product',
        icon: 'fi-rr-flower-bouquet',
        index: 13,
        menus: [
          {
            type: 'menu',
            title: 'Product',
            screen: 'sls.mst.product',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Product Branch',
            screen: 'sap.sls.mst.product_branch',
            index: 1,
          },
          {
            type: 'menu',
            title: 'UoM',
            screen: 'sls.mst.uom',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Category',
            screen: 'sap.sls.mst.category',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Brand',
            screen: 'sap.sls.mst.brand',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Principal',
            screen: 'sap.sls.mst.principal',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Division',
            screen: 'sls.mst.division',
            index: 6,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Pricing',
        icon: 'fi-rr-diamond',
        index: 14,
        menus: [
          {
            type: 'menu',
            title: 'Price Group',
            screen: 'sap.sls.mst.price_group',
            index: 0,
          },
          {
            type: 'menu',
            title: 'By Price Group',
            screen: 'sap.sls.mst.pricing.by_price_group',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Mark Customer Group',
            screen: 'sap.sls.mst.mark_customer_group',
            index: 2,
          },
          {
            type: 'menu',
            title: 'By Customer',
            screen: 'sap.sls.mst.picing.by_customer',
            index: 3,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Salesman',
        icon: 'fi-rr-user',
        index: 15,
        menus: [
          {
            type: 'menu',
            title: 'Salesman ID',
            screen: 'sap.sls.mst.salesman_id',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Division Salesman',
            screen: 'sap.sls.mst.salesman_division',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Salesman Group',
            screen: 'sap.sls.mst.salesman_group',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Transportation',
        icon: 'fi-rr-school-bus',
        index: 16,
        menus: [
          {
            type: 'menu',
            title: 'Vehicle',
            screen: 'sls.transp.vehicle',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Vehicle Type',
            screen: 'sls.transp.vehicle_type',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Shipping Type',
            screen: 'sls.transp.shipping_type',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Shipping Condition',
            screen: 'sls.transp.ship_condition',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Mode Of Transportation',
            screen: 'sls.transp.mode_of_transp',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Transportation Group ',
            screen: 'sls.transp.trans_group',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Transportation Zone',
            screen: 'sls.transp.trans_zone',
            index: 6,
          },
          {
            type: 'menu',
            title: 'Route',
            screen: 'sls.transp.route',
            index: 7,
          },
          {
            type: 'menu',
            title: 'Route Determination',
            screen: 'sls.transp.route_determination',
            index: 8,
          },
        ],
      },
      {
        type: 'title',
        title: '_________________________________',
        icon: '',
        index: 17,
      },
      {
        type: 'title',
        title: 'SFA Module',
        icon: '',
        index: 18,
      },
      {
        type: 'submodule',
        title: 'Call Plan',
        icon: 'fi-rr-calendar',
        index: 19,
        menus: [
          {
            type: 'menu',
            title: 'Call Plan Pattern',
            screen: 'sfa.callplan.pattern',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Call Plan List',
            screen: 'sfa.callplan',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Non Call Plan List',
            screen: 'sfa.noncallplan',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Attendance',
        icon: 'fi-rr-stopwatch',
        index: 20,
        menus: [
          {
            type: 'menu',
            title: 'Attendance',
            screen: 'sfa.attendance',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Sales Mapping',
        icon: 'fi-rr-layout-fluid',
        index: 21,
        menus: [
          {
            type: 'menu',
            title: 'Salesman Division',
            screen: 'sfa.salesman_division',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Salesman Division Product',
            screen: 'sfa.salesman_division_product',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Product Mapping',
        icon: 'fi-rr-flag',
        index: 22,
        menus: [
          {
            type: 'menu',
            title: 'Product Focus',
            screen: 'sfa.product.focus',
            index: 0,
          },
          {
            type: 'menu',
            title: 'New Product List',
            screen: 'sls.product.npl',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Target',
        icon: 'fi-rr-target',
        index: 23,
        menus: [
          {
            type: 'menu',
            title: 'Omset',
            screen: 'sfa.target.omset',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Effective Call',
            screen: 'sfa.target.effective_call',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Item Per Transaction',
            screen: 'sfa.target.item_per_transaction',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Register Outlet Active',
            screen: 'sfa.target.register_outlet_active',
            index: 3,
          },
          {
            type: 'menu',
            title: 'New Open Outlet',
            screen: 'sfa.target.new_open_outlet',
            index: 4,
          },
          {
            type: 'menu',
            title: 'New Product Launch',
            screen: 'sfa.target.new_product_launch',
            index: 5,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Collection',
        icon: 'fi-rr-bread-slice',
        index: 24,
        menus: [
          {
            type: 'menu',
            title: 'Collector',
            screen: 'sls.collection.collector',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Billing Mapping',
            screen: 'sfa.collection.billing_mapping',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Customer Payment Mapping',
            screen: 'sfa.collection.customer_payment',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Billing Schedule',
            screen: 'sfa.collection.billing_schedule',
            index: 3,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Competitor',
        icon: '',
        index: 25,
        menus: [
          {
            type: 'menu',
            title: 'Competitor',
            screen: 'sfa.competitor',
            index: 0,
          },
        ],
      },
      {
        type: 'title',
        title: '_________________________________',
        icon: '',
        index: 26,
      },
      {
        type: 'submodule',
        title: 'Report',
        icon: '',
        index: 27,
        menus: [
          {
            type: 'menu',
            title: 'Report Frozen',
            screen: 'sls.report.frozen',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Report Sales ',
            screen: 'sls.report.sales',
            index: 1,
          },
        ],
      },
      {
        type: 'title',
        title: 'CONFIGURATION',
        icon: '',
        index: 28,
      },
      {
        type: 'submodule',
        title: 'General Setting',
        icon: 'fi-rr-settings',
        index: 29,
        menus: [
          {
            type: 'menu',
            title: 'General Settings',
            screen: 'sls.config.general_setting',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Mapping Condition Type to GL Account\n',
            screen: 'sls.config.cond_to_gl',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Order Control',
            screen: 'sls.config.order_control',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Print Invoice',
            screen: 'sls.config.print_invoice',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Auto Submit',
            screen: 'sls.config.auto_submit',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Internal Sales',
            screen: 'sls.config.internal_sales',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Partial Availability',
            screen: 'sls.config.partial_availability',
            index: 6,
          },
          {
            type: 'menu',
            title: 'Tax Regulator',
            screen: 'sls.config.tax_regulator',
            index: 7,
          },
          {
            type: 'menu',
            title: 'Extract Data',
            screen: 'sls.report.extract_data',
            index: 8,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Sales Order Block',
        icon: 'fi-rr-user-delete',
        index: 30,
        menus: [
          {
            type: 'menu',
            title: 'Approval SO Block',
            screen: 'sls.config.approval_so_block',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Sales Order Block By Material',
            screen: 'sls.soblock.1',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Sales Order Block By Channel',
            screen: 'sls.soblock.2',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Sales Order Block By Customer',
            screen: 'sls.soblock.3',
            index: 3,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    index: 9,
    group: 7,
    name: 'SFA-Mobile',
    key: 'msfa',
    children: [
      {
        type: 'title',
        title: 'SFA Salesman Take Order',
        icon: '',
        index: 0,
      },
      {
        type: 'submodule',
        title: 'Homepage Take Order',
        icon: '',
        index: 1,
        menus: [
          {
            type: 'menu',
            title: 'Homepage TO',
            screen: 'sfa.homepage.to',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Absensi',
        icon: '',
        index: 2,
        menus: [
          {
            type: 'menu',
            title: 'Absensi > Absensi History',
            screen: 'sfa.attendance_history',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Absensi > Absen IN/OUT',
            screen: 'sfa.attendance_in_out',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'NOO',
        icon: '',
        index: 3,
        menus: [
          {
            type: 'menu',
            title: 'NOO > List NOO',
            screen: 'sfa.to.list_noo',
            index: 0,
          },
          {
            type: 'menu',
            title: 'NOO > Registrasi NOO',
            screen: 'sfa.to.regis_noo',
            index: 1,
          },
          {
            type: 'menu',
            title: 'NOO > Detail NOO',
            screen: 'sfa.to.detail_noo',
            index: 2,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Stok Produk',
        icon: '',
        index: 4,
        menus: [
          {
            type: 'menu',
            title: 'Produk > Produk',
            screen: 'sfa.to.master_product',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Outlet',
        icon: '',
        index: 5,
        menus: [
          {
            type: 'menu',
            title: 'Kunjungan Toko > List Kunjungan Toko / List Outlet',
            screen: 'sfa.to.callplans.list',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Kunjungan Toko',
        icon: '',
        index: 6,
        menus: [
          {
            type: 'menu',
            title: 'Kunjungan Toko > Lewati',
            screen: 'sfa.to.skip_visit',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Kunjungan Toko > Retur',
            screen: 'sfa.to.retur_quote',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Kunjungan Toko > Ambil Pesanan',
            screen: 'sfa.to.take_order_quote',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Kunjungan Toko > Detail Toko',
            screen: 'sfa.to.detail_store',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Kunjungan Toko > Tambah Kunjungan Toko',
            screen: 'sfa.to.add_call_plan',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Kunjungan Toko > List Kunjungan Toko / List Outlet',
            screen: 'sfa.to.callplans.list',
            index: 5,
          },
          {
            type: 'menu',
            title: 'Kunjungan Toko > Kunjungi / Take Order / Retur / Swap / Lewati',
            screen: 'sfa.to.visit',
            index: 6,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Promo',
        icon: '',
        index: 7,
        menus: [
          {
            type: 'menu',
            title: 'Promo > Promo List',
            screen: 'sfa.to.promo.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Promo > Promo Detail',
            screen: 'sfa.to.promo.detail',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Order Tracking',
        icon: '',
        index: 8,
        menus: [
          {
            type: 'menu',
            title: 'Order Tracking > List Order Tracking',
            screen: 'sfa.to.order_tracking.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Order Tracking > Detail Order Tracking',
            screen: 'sfa.to.order_tracking.detail',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Target',
        icon: '',
        index: 9,
        menus: [
          {
            type: 'menu',
            title: 'Target > Target Omset',
            screen: 'sfa.to.target_omset',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Target > Target NOO',
            screen: 'sfa.to.target_noo',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Target > Target ROA',
            screen: 'sfa.to.target_roa',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Target > Target IPT',
            screen: 'sfa.to.target_ipt',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Target > Target EC',
            screen: 'sfa.to.target_ec',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Target > Target NPL',
            screen: 'sfa.to.target_npl',
            index: 5,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Option',
        icon: '',
        index: 10,
        menus: [
          {
            type: 'menu',
            title: 'Option > Option Region',
            screen: 'sfa.to.option',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Reason',
        icon: '',
        index: 11,
        menus: [
          {
            type: 'menu',
            title: 'Reason List',
            screen: 'sfa.reason.list',
            index: 0,
          },
        ],
      },
      {
        type: 'title',
        title: '_________________________________',
        icon: '',
        index: 12,
      },
      {
        type: 'title',
        title: 'SFA Kepala Gudang',
        icon: '',
        index: 13,
      },
      {
        type: 'submodule',
        title: 'Homepage Kepala Gudang',
        icon: '',
        index: 14,
        menus: [
          {
            type: 'menu',
            title: 'Homepage Kag',
            screen: 'sfa.homepage.kag',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Absensi',
        icon: '',
        index: 15,
        menus: [
          {
            type: 'menu',
            title: 'Absensi > Absensi History',
            screen: 'sfa.attendance_history',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Absensi > Absen IN/OUT',
            screen: 'sfa.attendance_in_out',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Loading',
        icon: '',
        index: 16,
        menus: [
          {
            type: 'menu',
            title: 'Loading & Unloading > List Loading Barang Driver',
            screen: 'sfa.loading.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Loading & Unloading > Detail Loading Barang Driver',
            screen: 'sfa.loading.detail',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Unloading',
        icon: '',
        index: 17,
        menus: [
          {
            type: 'menu',
            title: 'Loading & Unloading > List Unloading',
            screen: 'sfa.unloading.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Loading & Unloading > Detail Unloading',
            screen: 'sfa.unloading.detail',
            index: 1,
          },
        ],
      },
      {
        type: 'title',
        title: '_________________________________',
        icon: '',
        index: 19,
      },
      {
        type: 'title',
        title: 'SFA Driver',
        icon: '',
        index: 20,
      },
      {
        type: 'submodule',
        title: 'Homepage Driver',
        icon: '',
        index: 21,
        menus: [
          {
            type: 'menu',
            title: 'Dasboard Driver / Count Progress Delivery',
            screen: 'sfa.drv.dashboard',
            index: 0,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Absensi',
        icon: '',
        index: 22,
        menus: [
          {
            type: 'menu',
            title: 'Absensi > Absensi History',
            screen: 'sfa.attendance_history',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Absensi > Absen IN/OUT',
            screen: 'sfa.attendance_in_out',
            index: 1,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Loading & Unloading',
        icon: '',
        index: 23,
        menus: [
          {
            type: 'menu',
            title: 'Loading & Unloading > List Loading Barang Driver',
            screen: 'sfa.loading.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Loading & Unloading > Detail Loading Barang Driver',
            screen: 'sfa.loading.detail',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Loading & Unloading > List Unloading',
            screen: 'sfa.unloading.list',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Loading & Unloading > Detail Unloading',
            screen: 'sfa.unloading.detail',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Loading & Unloading > Finish Unloading',
            screen: 'sfa.drv.unloading.finish',
            index: 4,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Delivery',
        icon: '',
        index: 24,
        menus: [
          {
            type: 'menu',
            title: 'Delivery > List Delivery',
            screen: 'sfa.drv.delivery.list',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Delivery > List Store Delivery',
            screen: 'sfa.drv.delivery.store_list',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Delivery > Detail Store Delivery',
            screen: 'sfa.drv.delivery.store_detail',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Delivery > Finish Shipment',
            screen: 'sfa.drv.delivery.finish_shipment',
            index: 3,
          },
          {
            type: 'menu',
            title: 'Delivery > Skip Visit Store',
            screen: 'sfa.drv.delivery.store_skip',
            index: 4,
          },
          {
            type: 'menu',
            title: 'Delivery > Titip Retur',
            screen: 'sfa.drv.delivery.take_a_return',
            index: 11,
          },
          {
            type: 'menu',
            title: 'Delivery > Cancel Billing',
            screen: 'sfa.drv.delivery.cancel_billing',
            index: 13,
          },
        ],
      },
      {
        type: 'submodule',
        title: 'Setoran',
        icon: '',
        index: 25,
        menus: [
          {
            type: 'menu',
            title: 'Setoran > Method Collection Driver',
            screen: 'sfa.drv.payment_method',
            index: 0,
          },
          {
            type: 'menu',
            title: 'Setoran > List Collection Driver',
            screen: 'sfa.drv.collection_list',
            index: 1,
          },
          {
            type: 'menu',
            title: 'Setoran > Detail Collection Driver',
            screen: 'sfa.drv.collection_detail',
            index: 2,
          },
          {
            type: 'menu',
            title: 'Setoran > Finish Collection Driver',
            screen: 'sfa.drv.finish_collection',
            index: 3,
          },
        ],
      },
    ],
  },
]
