export { default as ILJobAnalysis } from './ic-hc-job-analysis.svg'
export { default as ILJobEvaluation } from './ic-hc-job-evaluation.svg'
export { default as ILHCMapping } from './ic-hc-mapping.svg'
export { default as ILHCMission } from './ic-hc-mission.svg'
export { default as ILHCThankYou } from './ic-hc-thank-you.svg'
export { default as ILHCVision } from './ic-hc-vision.svg'
export { default as ILHCWFH } from './ic-hc-wfh.svg'
export { default as ILHCWFO } from './ic-hc-wfo.svg'